#!/usr/bin/env bash

# Run the live Quest RPC/RLS contract suite against a disposable local
# Supabase database. A fresh volume receives the checked-in migrations before
# the suite runs, and its volumes are deleted on exit.

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
MOBILE_DIR="$(cd -- "$SCRIPT_DIR/.." && pwd)"
MIGRATIONS_DIR="$MOBILE_DIR/supabase/migrations"
ENV_FILE="${RUNNER_TEMP:-${TMPDIR:-/tmp}}/quest-supabase.env"
LOCAL_METADATA_DIR="$MOBILE_DIR/supabase/.temp"
LOCAL_METADATA_BACKUP="${ENV_FILE}.metadata"
LOCAL_METADATA_MOVED=false
LOCAL_METADATA_FILES=(
  storage-version
  linked-project.json
  gotrue-version
  pooler-url
  postgres-version
  cli-latest
  project-ref
)
SUPABASE_STARTED=false
SUPABASE_CLI_VERSION="${SUPABASE_CLI_VERSION:-2.115.0}"

cleanup() {
  if [[ "$SUPABASE_STARTED" == true ]]; then
    (
      cd "$MOBILE_DIR"
      run_supabase stop --no-backup
    ) || echo "Warning: failed to remove disposable Supabase containers." >&2
  fi
  if [[ "$LOCAL_METADATA_MOVED" == true ]]; then
    for metadata_file in "${LOCAL_METADATA_FILES[@]}"; do
      if [[ -f "$LOCAL_METADATA_BACKUP/$metadata_file" ]]; then
        rm -f "$LOCAL_METADATA_DIR/$metadata_file"
        mv "$LOCAL_METADATA_BACKUP/$metadata_file" "$LOCAL_METADATA_DIR/$metadata_file"
      fi
    done
    rmdir "$LOCAL_METADATA_BACKUP" 2>/dev/null || true
  fi
  rm -f "$ENV_FILE"
}
trap cleanup EXIT

if [[ ! -f "$MOBILE_DIR/supabase/config.toml" ]]; then
  echo "Missing artifacts/mobile/supabase/config.toml." >&2
  exit 1
fi

# Validate the checked-in history before invoking the Supabase CLI. This keeps
# malformed and colliding versions from reaching disposable database
# provisioning, and uses the same validator as the hosted-project check.
node "$SCRIPT_DIR/validate-supabase-migrations.js" "$MIGRATIONS_DIR"

if command -v supabase >/dev/null 2>&1; then
  SUPABASE_CMD=(supabase)
elif command -v npx >/dev/null 2>&1; then
  SUPABASE_CMD=(npx --yes "supabase@${SUPABASE_CLI_VERSION}")
else
  echo "Quest database check requires the Supabase CLI." >&2
  exit 1
fi

run_supabase() {
  "${SUPABASE_CMD[@]}" "$@"
}

CLI_VERSION="$(run_supabase --version | tail -n 1 | sed -E 's/^supabase version //; s/^[[:space:]]+//; s/[[:space:]]+$//')"
if [[ -z "$CLI_VERSION" || "$CLI_VERSION" == "supabase version" ]]; then
  echo "Unable to determine the installed Supabase CLI version." >&2
  exit 1
fi
if [[ "$SUPABASE_CLI_VERSION" != "latest" && "$CLI_VERSION" != "$SUPABASE_CLI_VERSION" ]]; then
  echo "Quest database check requires Supabase CLI ${SUPABASE_CLI_VERSION}; found ${CLI_VERSION}." >&2
  echo "Install the pinned version or set SUPABASE_CLI_VERSION when deliberately testing an update." >&2
  exit 1
fi
if [[ "$SUPABASE_CLI_VERSION" == "latest" ]]; then
  echo "Testing candidate Supabase CLI ${CLI_VERSION} (resolved from latest)."
else
  echo "Testing Supabase CLI ${CLI_VERSION}."
fi

cd "$MOBILE_DIR"
# Generated Supabase metadata can point at the linked hosted project's service
# versions or internal migrations. Keep all of it out of this disposable
# provisioning run, then restore it in cleanup.
mkdir -p "$LOCAL_METADATA_BACKUP"
for metadata_file in "${LOCAL_METADATA_FILES[@]}"; do
  if [[ -f "$LOCAL_METADATA_DIR/$metadata_file" ]]; then
    mv "$LOCAL_METADATA_DIR/$metadata_file" "$LOCAL_METADATA_BACKUP/$metadata_file"
  fi
done
LOCAL_METADATA_MOVED=true
# Delete any volume from an interrupted prior run before provisioning the
# disposable project. `supabase start` then applies every migration to the
# fresh database as part of initialization.
run_supabase stop --no-backup >/dev/null 2>&1 || true
SUPABASE_STARTED=true
# The CLI can report a false-negative container health status while its Auth
# service is still completing first-run setup. We verify the Auth endpoint
# ourselves below and fail closed if it never becomes available.
run_supabase start --ignore-health-check

run_supabase status --output env > "$ENV_FILE"
# The status output is generated by the local CLI and is safe to source. Keep
# it in a temporary file so ephemeral service keys never enter the repository.
set -a
# shellcheck disable=SC1090
source "$ENV_FILE"
set +a

: "${API_URL:?Supabase status did not provide API_URL}"
: "${ANON_KEY:?Supabase status did not provide ANON_KEY}"
: "${SERVICE_ROLE_KEY:?Supabase status did not provide SERVICE_ROLE_KEY}"

export QUEST_TEST_SUPABASE_URL="$API_URL"
export QUEST_TEST_SUPABASE_ANON_KEY="$ANON_KEY"
export QUEST_TEST_SUPABASE_SERVICE_ROLE_KEY="$SERVICE_ROLE_KEY"
export QUEST_TEST_DB_URL="$DB_URL"
export SUPABASE_URL="$API_URL"
export SUPABASE_SERVICE_ROLE_KEY="$SERVICE_ROLE_KEY"

for attempt in {1..60}; do
  if curl --fail --silent --show-error "$API_URL/auth/v1/health" >/dev/null; then
    break
  fi
  if [[ "$attempt" == 60 ]]; then
    echo "Disposable Supabase Auth did not become healthy in time." >&2
    exit 1
  fi
  sleep 2
done

echo "Running Quest RPC and RLS contracts against the disposable database."
pnpm exec jest --runInBand __tests__/questRpc.integration.test.ts

echo "Running method-driven Quest verification contracts against the disposable database."
pnpm exec jest --runInBand __tests__/questVerification.integration.test.ts

echo "Running activity tracking validation, persistence, and idempotency contracts against the disposable database."
pnpm exec jest --runInBand __tests__/questActivityTracking.integration.test.ts

echo "Running moderator cleanup operator actions against the disposable database."
pnpm exec jest --runInBand __tests__/moderationMediaRetention.integration.test.ts

echo "Running rejected-media Storage access and retention contracts against the disposable database."
pnpm --filter @workspace/api-server test