import { useEffect, useMemo, useState } from 'react';
import { Link, useLocation } from 'wouter';
import { AlertTriangle, ArrowUpRight, Check, ChevronLeft, ChevronRight, Database, FileText, Flag, LockKeyhole, Plus, Search, ShieldCheck, SlidersHorizontal, UsersRound } from 'lucide-react';
import { useAdminData } from '@/hooks/use-admin-data';
import { DiagnosticsList, ErrorState, MetricGrid, PageHeader, QueueList, RefreshButton, StatusBadge, UnavailableState } from '@/components/admin-ui';
import { moderationFetch, type MediaRetentionEvidence, type QuestVerificationUpdate, type AdminQuestCreate } from '@/hooks/use-admin-data';
import { useQuery } from '@tanstack/react-query';

type AdminData = ReturnType<typeof useAdminData>;

const fmtDate = (value?: string | null) => value ? new Date(value).toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' }) : '—';
const fmtDateTime = (value?: string | null) => value ? new Date(value).toLocaleString(undefined, { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' }) : '—';
const initials = (name: string) => name.split(/\s+/).slice(0, 2).map((part) => part[0]).join('').toUpperCase();

export function DashboardPage({ data }: { data: AdminData }) {
  const dashboard = data.dashboard.data;
  const queues = data.reviewQueues.data?.queues;
  return (
    <div className="page-wrap">
      <PageHeader eyebrow="Workspace / today" title="Good morning, operator." description="A concise view of what needs attention across the Worlds platform." actions={<RefreshButton onClick={() => { void data.dashboard.refetch(); void data.reviewQueues.refetch(); }} loading={data.dashboard.isFetching} />} />
      <div style={{ display: 'flex', alignItems: 'center', gap: 7, color: 'hsl(var(--muted-foreground))', fontSize: 11, margin: '24px 0 12px' }}>
        <span className="status-dot" style={{ width: 6, height: 6 }} /> Last generated {dashboard?.generatedAt ? fmtDateTime(dashboard.generatedAt) : '—'}
      </div>
      <MetricGrid metrics={dashboard?.metrics} loading={data.dashboard.isLoading} />
      <div className="content-grid">
       <section className="panel">
          <div className="panel-header"><div><div className="panel-title">Priority queue</div><div className="panel-kicker">Items ordered by operational urgency</div></div><Link href="/quests/submissions" className="btn btn-quiet" style={{ minHeight: 32, padding: '0 9px' }} data-testid="link-view-all-queue">View queue <ArrowUpRight /></Link></div>
          {data.dashboard.isError ? <ErrorState onRetry={() => void data.dashboard.refetch()} /> : <QueueList items={dashboard?.actionQueue} loading={data.dashboard.isLoading} onRetry={() => void data.dashboard.refetch()} />}
        </section>
        <section className="panel">
          <div className="panel-header"><div><div className="panel-title">Review queues</div><div className="panel-kicker">Current moderation lanes</div></div><SlidersHorizontal style={{ width: 15, color: 'hsl(var(--muted-foreground))' }} /></div>
          <QueueList items={queues} loading={data.reviewQueues.isLoading} onRetry={() => void data.reviewQueues.refetch()} />
        </section>
      </div>
      <div className="notice" style={{ marginTop: 18 }}><Database /><span><strong>Operational note:</strong> dashboard figures are read-only snapshots generated by the platform. A missing value means the underlying service is unavailable, not zero.</span></div>
    </div>
  );
}

export function UsersPage({ data }: { data: AdminData }) {
  const [search, setSearch] = useState('');
  const [status, setStatus] = useState('all');
  const users = data.users.data?.items;
  const filtered = useMemo(() => users?.filter((user: any) => `${user.displayName} ${user.username} ${user.role}`.toLowerCase().includes(search.toLowerCase()) && (status === 'all' || user.accountStatus === status)), [users, search, status]);
  const statuses = Array.from(new Set(users?.map((user: any) => user.accountStatus) || [])) as string[];
  return (
    <div className="page-wrap">
      <PageHeader eyebrow="Operations / people" title="User directory" description="Search staff-facing identity and activity signals without leaving the operations console." actions={<RefreshButton onClick={() => void data.users.refetch()} loading={data.users.isFetching} />} />
      <div className="toolbar">
        <div className="search-box"><Search /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search by name or username" aria-label="Search users" data-testid="input-search-users" /></div>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}><label className="eyebrow" htmlFor="user-status-filter">Status</label><select id="user-status-filter" value={status} onChange={(event) => setStatus(event.target.value)} style={{ border: '1px solid hsl(var(--input))', background: 'hsl(var(--card))', borderRadius: 6, padding: '9px 10px', color: 'hsl(var(--foreground))', fontSize: 12 }} data-testid="select-user-status"><option value="all">All accounts</option>{statuses.map((item) => <option value={item} key={item}>{item.replace(/_/g, ' ')}</option>)}</select></div>
      </div>
      <section className="panel">
        <div className="panel-header"><div><div className="panel-title">All users</div><div className="panel-kicker">{data.users.data?.total ?? '—'} records returned · page 1</div></div><UsersRound style={{ width: 17, color: 'hsl(var(--muted-foreground))' }} /></div>
        {data.users.isError ? <ErrorState onRetry={() => void data.users.refetch()} /> : data.users.isLoading ? <TableSkeleton columns={5} /> : !users ? <UnavailableState onRetry={() => void data.users.refetch()} /> : !filtered?.length ? <div className="empty-state"><Search /><strong>No matching users</strong><p>Try a different name, username, or account status.</p></div> : <div className="data-table-wrap"><table className="data-table"><thead><tr><th>Identity</th><th>Role</th><th>Account</th><th>Activity</th><th>Points</th><th>Open cases</th></tr></thead><tbody>{filtered.map((user: any) => <tr key={user.id} data-testid={`row-user-${user.id}`}><td><div className="identity"><div className="avatar">{initials(user.displayName)}</div><div><div className="identity-name" data-testid={`text-user-name-${user.id}`}>{user.displayName}</div><div className="identity-handle">@{user.username}</div></div></div></td><td><StatusBadge status={user.role} /></td><td><StatusBadge status={user.accountStatus} /></td><td><div style={{ fontWeight: 600 }}>{fmtDate(user.lastActiveAt)}</div><div className="identity-handle">Joined {fmtDate(user.createdAt)}</div></td><td className="mono">{user.totalPoints ?? '—'}</td><td><span className={user.openCases ? 'tag red' : 'tag'}>{user.openCases ?? '—'}</span></td></tr>)}</tbody></table></div>}
      </section>
    </div>
  );
}

export function QuestsPage({ data }: { data: AdminData }) {
  const [search, setSearch] = useState('');
  const [type, setType] = useState('all');
  const [showCreate, setShowCreate] = useState(false);
  const quests = data.quests.data?.items;
  const filtered = useMemo(() => quests?.filter((quest: any) => `${quest.title} ${quest.source}`.toLowerCase().includes(search.toLowerCase()) && (type === 'all' || quest.type === type)), [quests, search, type]);
  return (
    <div className="page-wrap">
      <PageHeader eyebrow="Operations / content" title="Quest administration" description="Review the content pipeline, publishing state, and proof load across every Quest format." actions={<div style={{ display: 'flex', gap: 8 }}><button className="btn btn-primary" onClick={() => setShowCreate((value) => !value)} disabled={!data.session.data?.permissions.includes('admin.quests.manage')}><Plus style={{ width: 14 }} /> New Quest</button><RefreshButton onClick={() => void data.quests.refetch()} loading={data.quests.isFetching} /></div>} />
      {showCreate && <AdminQuestCreateForm data={data} onCreated={() => setShowCreate(false)} />}
      <div className="tab-row" data-testid="quest-section-tabs"><Link className={`tab ${type === 'all' ? 'active' : ''}`} href="/quests" data-testid="link-quest-tab-all">All quests</Link><Link className="tab" href="/quests/daily" data-testid="link-quest-tab-daily">Daily</Link><Link className="tab" href="/quests/monthly" data-testid="link-quest-tab-monthly">Monthly</Link><Link className="tab" href="/quests/geo" data-testid="link-quest-tab-geo">Geo</Link><Link className="tab" href="/quests/submissions" data-testid="link-quest-tab-submissions">Proof review</Link></div>
      <div className="toolbar"><div className="search-box"><Search /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search Quest title or source" aria-label="Search quests" data-testid="input-search-quests" /></div><select value={type} onChange={(event) => setType(event.target.value)} style={{ border: '1px solid hsl(var(--input))', background: 'hsl(var(--card))', borderRadius: 6, padding: '9px 10px', color: 'hsl(var(--foreground))', fontSize: 12 }} data-testid="select-quest-type"><option value="all">Every type</option><option value="daily">Daily</option><option value="monthly">Monthly</option><option value="geo">Geo</option></select></div>
      <section className="panel">
        <div className="panel-header"><div><div className="panel-title">Quest catalog</div><div className="panel-kicker">{data.quests.data?.total ?? '—'} records returned · sorted by latest update</div></div><TargetIcon /></div>
         {data.quests.isError ? <ErrorState onRetry={() => void data.quests.refetch()} /> : data.quests.isLoading ? <TableSkeleton columns={7} /> : !quests ? <UnavailableState onRetry={() => void data.quests.refetch()} /> : !filtered?.length ? <div className="empty-state"><Search /><strong>No matching Quests</strong><p>There are no records matching this search and type filter.</p></div> : <div className="data-table-wrap"><table className="data-table"><thead><tr><th>Quest</th><th>Type</th><th>Status</th><th>Difficulty</th><th>Verification</th><th>Completions</th><th>Reviews</th><th>Updated</th></tr></thead><tbody>{filtered.map((quest: any) => <tr key={quest.id} data-testid={`row-quest-${quest.id}`}><td><div className="identity-name">{quest.title}</div><div className="identity-handle">{quest.source} · {quest.points ?? '—'} pts</div></td><td><span className="tag blue">{quest.type}</span></td><td><StatusBadge status={quest.status} /></td><td>{quest.difficulty || '—'}</td><td><QuestVerificationEditor quest={quest} data={data} /></td><td className="mono">{quest.completionCount ?? '—'}</td><td className="mono">{quest.reviewCount ?? '—'}</td><td>{fmtDate(quest.updatedAt)}</td></tr>)}</tbody></table></div>}
      </section>
    </div>
  );
}

function AdminQuestCreateForm({ data, onCreated }: { data: AdminData; onCreated: () => void }) {
  const [draft, setDraft] = useState<AdminQuestCreate>({
    title: '', type: 'daily', difficulty: 'easy', points: 100, methods: ['integrity_confirmation'],
    requiredDurationMinutes: null,
  });
  const [message, setMessage] = useState('');
  const toggle = (method: QuestVerificationUpdate['methods'][number]) => setDraft((current) => ({
    ...current,
    methods: current.methods.includes(method) ? current.methods.filter((item) => item !== method) : [...current.methods, method],
  }));
  const save = () => {
    setMessage('');
    if (draft.methods.length === 0) { setMessage('Choose at least one verification method.'); return; }
    if (draft.type === 'geo' && !draft.methods.includes('gps')) { setMessage('Geo Quests require GPS verification.'); return; }
    if (draft.methods.includes('gps') && draft.type !== 'geo') { setMessage('GPS verification is only available for Geo Quests.'); return; }
    if (draft.methods.includes('timer') && (!draft.requiredDurationMinutes || draft.requiredDurationMinutes < 1)) { setMessage('Timer duration must be at least 1 minute.'); return; }
    data.createQuest.mutate(draft, {
      onSuccess: () => onCreated(),
      onError: (error) => setMessage(error instanceof Error ? error.message : 'Could not create Quest.'),
    });
  };
  return <section className="panel" style={{ marginTop: 20 }}>
    <div className="panel-header"><div><div className="panel-title">Create Quest draft</div><div className="panel-kicker">New content starts as draft and cannot publish without review.</div></div><Plus style={{ width: 16 }} /></div>
    <div className="toolbar">
      <label className="field">Title<input value={draft.title} onChange={(event) => setDraft({ ...draft, title: event.target.value })} placeholder="A clear player-facing title" /></label>
      <label className="field">Type<select value={draft.type} onChange={(event) => setDraft({ ...draft, type: event.target.value as AdminQuestCreate['type'] })}><option value="daily">Daily</option><option value="monthly">Monthly</option><option value="geo">Geo</option></select></label>
      <label className="field">Difficulty<select value={draft.difficulty} onChange={(event) => setDraft({ ...draft, difficulty: event.target.value as AdminQuestCreate['difficulty'] })}><option value="easy">Easy</option><option value="medium">Medium</option><option value="hard">Hard</option><option value="epic">Epic</option></select></label>
      <label className="field">Points<input type="number" min="1" max="1000" value={draft.points} onChange={(event) => setDraft({ ...draft, points: Number(event.target.value) })} /></label>
    </div>
    <div className="toolbar">
      <div className="field"><span>Verification methods</span><div style={{ display: 'flex', flexWrap: 'wrap', gap: 5 }}>{verificationOptions.map((option) => <button key={option.value} type="button" className={`tag ${draft.methods.includes(option.value) ? 'blue' : ''}`} onClick={() => toggle(option.value)} aria-pressed={draft.methods.includes(option.value)}>{option.label}</button>)}</div></div>
      {draft.methods.includes('timer') && <label className="field">Timer minutes<input type="number" min="1" max="1440" value={draft.requiredDurationMinutes ?? ''} onChange={(event) => setDraft({ ...draft, requiredDurationMinutes: Number(event.target.value) })} /></label>}
    </div>
    {message && <div className="notice" style={{ margin: '0 20px 16px' }}><AlertTriangle /><span>{message}</span></div>}
    <div className="panel-footer"><span className="identity-handle">The draft will be saved to the human review queue.</span><button className="btn btn-primary" onClick={save} disabled={data.createQuest.isPending || !draft.title.trim()}>{data.createQuest.isPending ? 'Creating…' : 'Create draft'}</button></div>
  </section>;
}

const verificationOptions: Array<{ value: QuestVerificationUpdate['methods'][number]; label: string }> = [
  { value: 'camera', label: 'Camera' }, { value: 'gps', label: 'GPS location' },
  { value: 'timer', label: 'Timer' }, { value: 'integrity_confirmation', label: 'Integrity only' },
];

function QuestVerificationEditor({ quest, data }: { quest: any; data: AdminData }) {
  const canManage = data.session.data?.authorized === true && data.session.data.permissions.includes('admin.quests.manage');
  const initial = (Array.isArray(quest.verificationMethods) && quest.verificationMethods.length ? quest.verificationMethods : ['camera']) as QuestVerificationUpdate['methods'];
  const [methods, setMethods] = useState<QuestVerificationUpdate['methods']>(initial);
  const [duration, setDuration] = useState(String(quest.requiredDurationMinutes ?? ''));
  const [message, setMessage] = useState('');
  useEffect(() => {
    const nextMethods = Array.isArray(quest.verificationMethods) && quest.verificationMethods.length
      ? quest.verificationMethods as QuestVerificationUpdate['methods']
      : ['camera' as const];
    setMethods(nextMethods);
    setDuration(String(quest.requiredDurationMinutes ?? ''));
  }, [quest.verificationMethods, quest.requiredDurationMinutes]);
  const toggle = (method: QuestVerificationUpdate['methods'][number]) => {
    setMessage('');
    setMethods((current) => current.includes(method) ? current.filter((item) => item !== method) : [...current, method]);
  };
  const save = () => {
    setMessage('');
    if (!methods.length) { setMessage('Choose a method.'); return; }
    if (methods.includes('timer') && (!Number(duration) || Number(duration) < 1)) { setMessage('Timer must be at least 1 minute.'); return; }
    if (methods.includes('gps') && quest.type !== 'geo') { setMessage('GPS is only available for Geo Quests.'); return; }
    data.updateQuestVerification.mutate({ id: quest.id, update: { methods, requiredDurationMinutes: methods.includes('timer') ? Number(duration) : null, locationRequired: methods.includes('gps') } }, {
      onSuccess: () => setMessage('Saved.'), onError: (error) => setMessage(error instanceof Error ? error.message : 'Unable to save.'),
    });
  };
  return <div style={{ minWidth: 190 }}>
    <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4 }}>{verificationOptions.map((option) => <button key={option.value} type="button" className={`tag ${methods.includes(option.value) ? 'blue' : ''}`} onClick={() => toggle(option.value)} disabled={!canManage || data.updateQuestVerification.isPending} aria-pressed={methods.includes(option.value)}>{option.label}</button>)}</div>
    {methods.includes('timer') && <input type="number" min="1" max="1440" value={duration} onChange={(event) => setDuration(event.target.value)} placeholder="Minutes" aria-label={`Timer duration for ${quest.title}`} style={{ width: 90, marginTop: 6 }} disabled={!canManage} />}
    <div style={{ display: 'flex', alignItems: 'center', gap: 7, marginTop: 6 }}><button type="button" className="btn btn-primary" style={{ minHeight: 27, padding: '0 8px', fontSize: 11 }} onClick={save} disabled={!canManage || data.updateQuestVerification.isPending}>{data.updateQuestVerification.isPending ? 'Saving…' : 'Save'}</button>{message && <span className="identity-handle">{message}</span>}</div>
  </div>;
}

function TargetIcon() {
  return <div style={{ width: 29, height: 29, borderRadius: 7, background: 'hsl(var(--accent) / .16)', display: 'grid', placeItems: 'center', color: 'hsl(24 71% 41%)' }}><ArrowUpRight style={{ width: 15 }} /></div>;
}

function TableSkeleton({ columns }: { columns: number }) {
  return <div className="data-table-wrap"><table className="data-table"><tbody>{[1, 2, 3, 4, 5].map((row) => <tr key={row}>{Array.from({ length: columns }).map((_, col) => <td key={col}><div className="skeleton" style={{ height: 13, width: col === 0 ? '80%' : '52%' }} /></td>)}</tr>)}</tbody></table></div>;
}

export function AuditPage({ data }: { data: AdminData }) {
  const [search, setSearch] = useState('');
  const events = data.audit.data?.items;
  const filtered = events?.filter((event: any) => `${event.actor} ${event.action} ${event.entityType} ${event.entity}`.toLowerCase().includes(search.toLowerCase()));
  return (
    <div className="page-wrap">
      <PageHeader eyebrow="Platform / accountability" title="Audit log" description="An append-only view of staff actions and their recorded outcomes." actions={<RefreshButton onClick={() => void data.audit.refetch()} loading={data.audit.isFetching} />} />
      <div className="notice" style={{ marginTop: 25 }}><LockKeyhole /><span>Audit events are immutable. This view is for investigation and traceability; it does not expose controls to alter history.</span></div>
      <div className="toolbar"><div className="search-box"><Search /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search actor, action, or entity" aria-label="Search audit log" data-testid="input-search-audit" /></div><span className="mono" style={{ color: 'hsl(var(--muted-foreground))', fontSize: 10 }}>{data.audit.data?.total ?? '—'} EVENTS</span></div>
      <section className="panel">{data.audit.isError ? <ErrorState onRetry={() => void data.audit.refetch()} /> : data.audit.isLoading ? <TableSkeleton columns={5} /> : !events ? <UnavailableState onRetry={() => void data.audit.refetch()} /> : !filtered?.length ? <div className="empty-state"><FileLogIcon /><strong>No audit events found</strong><p>Nothing matches this search in the returned event page.</p></div> : <div className="data-table-wrap"><table className="data-table"><thead><tr><th>Timestamp</th><th>Actor</th><th>Action</th><th>Entity</th><th>Result</th><th>Reason</th></tr></thead><tbody>{filtered.map((event: any) => <tr key={event.id} data-testid={`row-audit-${event.id}`}><td className="mono" style={{ whiteSpace: 'nowrap', fontSize: 10 }}>{fmtDateTime(event.timestamp)}</td><td><div style={{ fontWeight: 600 }}>{event.actor || 'System'}</div><div className="identity-handle">{event.actorRole || '—'}</div></td><td>{event.action}</td><td>{event.entityType}{event.entity ? <div className="identity-handle">{event.entity}</div> : null}</td><td><StatusBadge status={event.result} /></td><td style={{ maxWidth: 240, color: 'hsl(var(--muted-foreground))' }}>{event.reason || '—'}</td></tr>)}</tbody></table></div>}</section>
    </div>
  );
}

function FileLogIcon() {
  return <FileText style={{ color: 'hsl(var(--accent))' }} />;
}

export function DiagnosticsPage({ data }: { data: AdminData }) {
  const diagnostics = data.diagnostics.data;
  const unavailableCount = diagnostics?.checks.filter((check: any) => ['missing', 'degraded', 'failed', 'unavailable'].includes(check.status)).length || 0;
  return (
    <div className="page-wrap">
      <PageHeader eyebrow="Platform / health" title="Diagnostics" description="Safe, read-only checks for the services that power staff operations." actions={<RefreshButton onClick={() => void data.diagnostics.refetch()} loading={data.diagnostics.isFetching} />} />
      <div style={{ display: 'flex', gap: 10, margin: '26px 0 17px', flexWrap: 'wrap' }}><span className="tag green" data-testid="status-diagnostics-summary">{diagnostics ? `${diagnostics.checks.length - unavailableCount} healthy` : 'Status unavailable'}</span>{diagnostics && unavailableCount > 0 && <span className="tag orange">{unavailableCount} need attention</span>}<span className="mono" style={{ alignSelf: 'center', fontSize: 10, color: 'hsl(var(--muted-foreground))' }}>{diagnostics?.generatedAt ? `Generated ${fmtDateTime(diagnostics.generatedAt)}` : 'Awaiting platform response'}</span></div>
      {data.diagnostics.isError ? <div className="panel"><ErrorState onRetry={() => void data.diagnostics.refetch()} /></div> : <DiagnosticsList checks={diagnostics?.checks} loading={data.diagnostics.isLoading} onRetry={() => void data.diagnostics.refetch()} />}
    </div>
  );
}

export function MediaRetentionPage({ data, page = 1, onPageChange }: { data: AdminData; page?: number; onPageChange?: (page: number) => void }) {
  const retention = data.mediaRetention.data;
  const items = retention?.items ?? [];
  const [selectedMediaId, setSelectedMediaId] = useState<string | null>(null);
  const evidence = useQuery<MediaRetentionEvidence>({
    queryKey: ['/admin/moderation/media-retention/evidence', selectedMediaId],
    enabled: Boolean(selectedMediaId) && data.session.data?.permissions.includes('moderation.read') === true,
    queryFn: () => moderationFetch<MediaRetentionEvidence>(`/api/admin/moderation/media-retention/${encodeURIComponent(selectedMediaId!)}`),
  });
  const evidenceData = evidence.data;
  const canManage = data.session.data?.permissions.includes('moderation.manage') === true;
  const list = retention?.list;
  const currentPage = list?.page ?? page;
  const goToPage = (nextPage: number) => {
    if (!onPageChange || nextPage < 1 || (list && nextPage > list.totalPages)) return;
    setSelectedMediaId(null);
    onPageChange(nextPage);
  };
  const takeAction = (action: 'requeue' | 'resolve') => {
    if (!evidenceData?.canonicalReference.fingerprint || !selectedMediaId || !canManage) return;
    const label = action === 'requeue' ? 'requeue this cleanup for the trusted worker' : 'mark this cleanup resolved without a Storage deletion';
    if (!window.confirm(`Confirm that the canonical media reference is correct and ${label}. This action is recorded and cannot be silently undone.`)) return;
    const reason = window.prompt('Resolution reason (required)');
    if (!reason?.trim()) return;
    data.mediaRetentionAction.mutate({
      mediaId: selectedMediaId,
      action,
      referenceFingerprint: evidenceData.canonicalReference.fingerprint,
      reason: reason.trim(),
    });
  };
  return (
    <div className="page-wrap">
      <PageHeader
        eyebrow="Review / storage"
        title="Media retention cleanup"
        description="Track rejected private-media cleanup without opening private media or exposing Storage paths."
        actions={<RefreshButton onClick={() => void data.mediaRetention.refetch()} loading={data.mediaRetention.isFetching} />}
      />
      <div className="metrics-grid" style={{ marginTop: 26 }}>
        {[
          ['Pending', retention?.summary.pending, 'Awaiting a worker claim'],
          ['Retrying', retention?.summary.retrying, 'Deletion or claim will retry'],
          ['Completed', retention?.summary.completed, 'Worker-confirmed terminal records'],
          ['Resolved', retention?.summary.resolved, 'Moderator-closed records'],
          ['Blocked references', retention?.summary.blocked, 'Manual review required'],
        ].map(([label, value, detail]) => (
          <div className="metric-card" key={String(label)} data-testid={`metric-retention-${String(label).toLowerCase().replace(/\s+/g, '-')}`}>
            <div className="metric-label">{label}</div>
            <div className="metric-value">{value ?? '—'}</div>
            <div className="metric-detail">{detail}</div>
          </div>
        ))}
      </div>
      <div className="notice" style={{ marginTop: 18 }}>
        <LockKeyhole />
        <span><strong>Privacy boundary:</strong> this view contains cleanup references and bounded error summaries only. It never returns private media, bucket names, or raw Storage paths.</span>
      </div>
      <section className="panel" style={{ marginTop: 22 }}>
        <div className="panel-header">
          <div><div className="panel-title">Cleanup history</div><div className="panel-kicker">{retention ? `${retention.summary.total} total records across all history · showing ${retention.list.returned} records on page ${currentPage} of ${retention.list.totalPages}` : 'Live worker state'}</div></div>
          <StatusBadge status={retention ? (retention.summary.blocked ? 'blocked' : 'healthy') : 'unavailable'} />
        </div>
        {data.mediaRetention.isError ? <ErrorState onRetry={() => void data.mediaRetention.refetch()} /> : data.mediaRetention.isLoading ? <TableSkeleton columns={8} /> : !retention ? <UnavailableState onRetry={() => void data.mediaRetention.refetch()} /> : !items.length ? <div className="empty-state"><Check /><strong>No cleanup records yet</strong><p>The worker has not recorded a rejected private-media cleanup.</p></div> : <div className="data-table-wrap"><table className="data-table"><thead><tr><th>State</th><th>Reference</th><th>Attempts</th><th>Last attempt</th><th>Next retry</th><th>Deletion result</th><th>Error summary</th><th>Evidence</th></tr></thead><tbody>{items.map((item) => <tr key={item.mediaId} data-testid={`row-retention-${item.mediaId}`}><td><StatusBadge status={item.state} /></td><td className="mono" title={item.mediaId}>{item.mediaId.slice(0, 8)}…</td><td className="mono">{item.attemptCount}</td><td>{fmtDateTime(item.lastAttemptAt)}</td><td>{fmtDateTime(item.nextAttemptAt)}</td><td>{item.deletionOutcome === 'missing' ? <span className="tag orange">Object missing · complete</span> : item.deletionOutcome === 'deleted' ? <span className="tag green">Deleted</span> : item.state === 'blocked' ? <span className="tag red">Blocked</span> : item.state === 'resolved' ? <span className="tag green">Resolved</span> : <span className="tag red">Deletion failed</span>}</td><td style={{ maxWidth: 310, color: 'hsl(var(--muted-foreground))' }}>{item.lastError || '—'}</td><td>{item.state === 'blocked' ? <button className="btn btn-quiet" onClick={() => setSelectedMediaId(item.mediaId)} data-testid={`button-retention-evidence-${item.mediaId}`}>Review</button> : '—'}</td></tr>)}</tbody></table></div>}
        {retention && (retention.list.totalPages > 1 || currentPage > 1) ? <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 12, marginTop: 16, flexWrap: 'wrap' }} data-testid="retention-pagination">
          <span className="panel-kicker">Page {currentPage} of {retention.list.totalPages} · {retention.list.offset + 1}–{retention.list.offset + retention.list.returned} of {retention.summary.total}</span>
          <div style={{ display: 'flex', gap: 8 }}>
            <button className="btn btn-quiet" onClick={() => goToPage(currentPage - 1)} disabled={data.mediaRetention.isFetching || currentPage <= 1 || !onPageChange} data-testid="button-retention-previous"><ChevronLeft /> Newer</button>
            <button className="btn btn-quiet" onClick={() => goToPage(currentPage + 1)} disabled={data.mediaRetention.isFetching || !retention.list.hasMore || !onPageChange} data-testid="button-retention-next">Older <ChevronRight /></button>
          </div>
        </div> : null}
      </section>
      {selectedMediaId ? <section className="panel" style={{ marginTop: 22 }} data-testid="panel-retention-evidence">
        <div className="panel-header">
          <div><div className="panel-title">Retention evidence</div><div className="panel-kicker mono">{selectedMediaId}</div></div>
          <button className="btn btn-quiet" onClick={() => setSelectedMediaId(null)}>Close</button>
        </div>
        {evidence.isLoading ? <div className="empty-state">Loading evidence…</div> : evidence.isError ? <ErrorState onRetry={() => void evidence.refetch()} /> : !evidenceData ? <UnavailableState onRetry={() => void evidence.refetch()} /> : <div className="content-grid">
          <div>
            {evidenceData.media.preview ? <img src={evidenceData.media.preview.signedUrl} alt="Moderation evidence" style={{ width: '100%', maxHeight: 280, objectFit: 'contain', borderRadius: 8, background: 'hsl(var(--muted))' }} /> : <div className="empty-state"><AlertTriangle /><strong>Preview unavailable</strong><p>The private object may already be missing.</p></div>}
            <div className="notice" style={{ marginTop: 14 }}><LockKeyhole /><span>Private Storage paths are never shown. The current canonical reference is represented by an opaque confirmation fingerprint.</span></div>
          </div>
          <div>
            <div className="panel-kicker">Media record</div>
            <p><strong>{evidenceData.media.mediaType}</strong> · {evidenceData.media.mimeType} · {evidenceData.media.purpose}</p>
            <p>Moderation: <StatusBadge status={evidenceData.media.moderationStatus} /> {evidenceData.media.moderationReason || 'No additional reason'}</p>
            <p>Cleanup: <StatusBadge status={evidenceData.cleanup.state} /> · {evidenceData.cleanup.attemptCount} attempts</p>
            <p>Canonical reference: <StatusBadge status={evidenceData.canonicalReference.matchesCleanup ? 'confirmed' : 'changed'} /></p>
            {evidenceData.moderationCases.length ? <><div className="panel-kicker" style={{ marginTop: 18 }}>Moderation cases</div>{evidenceData.moderationCases.map((item) => <div className="notice" key={item.id} style={{ marginTop: 8 }}><span><strong>{item.status}</strong>{item.decision ? ` · ${item.decision}` : ''}{item.decisionReason ? ` — ${item.decisionReason}` : ''}{item.riskCategories?.length ? ` · ${item.riskCategories.join(', ')}` : ''}</span></div>)}</> : <p className="identity-handle">No linked moderation case was returned.</p>}
            <div style={{ display: 'flex', gap: 8, marginTop: 20 }}>
              <button className="btn btn-primary" onClick={() => takeAction('requeue')} disabled={!canManage || !evidenceData.canonicalReference.fingerprint || data.mediaRetentionAction.isPending} data-testid="button-retention-requeue">Confirm reference & requeue</button>
              <button className="btn btn-quiet" onClick={() => takeAction('resolve')} disabled={!canManage || !evidenceData.canonicalReference.fingerprint || data.mediaRetentionAction.isPending} data-testid="button-retention-resolve">Resolve cleanup</button>
            </div>
            {!evidenceData.canonicalReference.matchesCleanup && <p className="identity-handle" style={{ marginTop: 10 }}>The cleanup is blocked because its saved reference differs from the current media record. Review the current record, then confirm the current reference before acting.</p>}
          </div>
        </div>}
      </section> : null}
      <div className="notice" style={{ marginTop: 18 }}><AlertTriangle /><span>“Object missing” is a successful idempotent terminal outcome. “Deletion failed” remains retryable; blocked references require manual review before the worker can proceed.</span></div>
    </div>
  );
}

type AiResponse = {
  provider?: { configured: boolean; provider: string | null; model: string | null };
  promptTemplates?: Array<{ type: string; versions: number; activeVersion: number | null }>;
  generationPolicy?: string;
  generatedAt?: string;
  items?: Array<Record<string, unknown>>;
  settings?: Record<string, unknown>;
  prompt?: AiPrompt & { type: string };
  plan?: { diagnostics?: string[]; replacementAllowed?: boolean; publishRequiresReview?: boolean };
  results?: Array<{ ok?: boolean; candidate?: Record<string, unknown>; review?: { diagnostics?: string[] } }>;
  draft?: { id: string; status: string; createdAt: string; reviewRequired: boolean };
  candidates?: Array<{ id: string; title: string; type: string | null; difficulty: string | null; points: number | null; status: string; reviewNotes: string | null; reviewedAt: string | null; createdAt: string }>;
  candidate?: { id: string; status: string; reviewedAt: string | null };
  message?: string;
  comparison?: { changedFields?: string[]; fields?: Array<{ field: string; changed: boolean; left: string; right: string }> };
};
type AiPrompt = {
  systemInstructions: string;
  contentInstructions: string;
  safetyInstructions: string;
  pointInstructions: string;
  proofInstructions: string;
  outputFormat: string;
  version?: number;
  active?: boolean;
};

async function aiFetch(path: string, init?: RequestInit): Promise<AiResponse> {
  const response = await fetch(`/api/admin/ai${path}`, { credentials: 'include', ...init, headers: { 'content-type': 'application/json', ...(init?.headers || {}) } });
  if (!response.ok) throw new Error(response.status === 503 ? 'AI services are unavailable until configured.' : 'AI request was not authorized.');
  return response.json() as Promise<AiResponse>;
}

export function AIPage({ data }: { data: AdminData }) {
  const [location] = useLocation();
  const [result, setResult] = useState<AiResponse | null>(null);
  const [loading, setLoading] = useState(true);
  const [message, setMessage] = useState('');
  const [type, setType] = useState<'daily' | 'monthly' | 'geo'>('daily');
  const [quantity, setQuantity] = useState('1');
  const [prompt, setPrompt] = useState<AiPrompt>({
    systemInstructions: '',
    contentInstructions: '',
    safetyInstructions: '',
    pointInstructions: '',
    proofInstructions: '',
    outputFormat: '',
  });
  const [interestCluster, setInterestCluster] = useState('');
  const [theme, setTheme] = useState('');
  const [targetMonth, setTargetMonth] = useState('');
  const [locationContext, setLocationContext] = useState('');
  const [approximateArea, setApproximateArea] = useState('');
  const [selectedVersion, setSelectedVersion] = useState('');
  const [compareVersion, setCompareVersion] = useState('');

  useEffect(() => {
    const requiredPermission = location === '/ai/generate'
      ? 'ai.generate'
      : location === '/ai/settings'
        ? 'ai.settings.read'
        : location === '/ai/prompts'
          ? 'ai.prompts.read'
          : 'ai.read';
    if (!data.session.data?.authorized || !data.session.data.permissions.includes(requiredPermission)) {
      setLoading(false);
      return;
    }
    let cancelled = false;
    const request = location === '/ai'
      ? Promise.all([aiFetch('/overview'), aiFetch('/candidates')]).then(([overview, review]) => ({ ...overview, ...review }))
      : aiFetch(location === '/ai/prompts' ? '/prompts' : location === '/ai/settings' ? '/settings' : '/history');
    void request
      .then((value) => { if (!cancelled) setResult(value); })
      .catch((error: Error) => { if (!cancelled) setMessage(error.message); })
      .finally(() => { if (!cancelled) setLoading(false); });
    return () => { cancelled = true; };
  }, [location]);

  useEffect(() => {
    const first = result?.items?.[0] as AiPrompt | undefined;
    if (first) {
      setPrompt(first);
      setSelectedVersion(String(first.version ?? ''));
    }
    if (result?.prompt) {
      setPrompt(result.prompt);
      setSelectedVersion(String(result.prompt.version));
    }
  }, [result]);

  const generate = async () => {
    setLoading(true);
    setMessage('');
    try {
      const variables = type === 'daily'
        ? { current_date: new Date().toISOString().slice(0, 10), interest_bubble_ids: JSON.stringify(interestCluster.split(',').map((value) => value.trim()).filter(Boolean)) }
        : type === 'monthly'
          ? { current_date: new Date().toISOString().slice(0, 10), theme, target_month: targetMonth }
          : { current_date: new Date().toISOString().slice(0, 10), public_location_context: locationContext, approximate_area: approximateArea };
      const value = await aiFetch('/generate', {
        method: 'POST',
        body: JSON.stringify({ type, quantity: Number(quantity), variables, testOnly: true }),
      });
      setResult(value);
    } catch (error) {
      setMessage(error instanceof Error ? error.message : 'Generation failed.');
    } finally {
      setLoading(false);
    }
  };

  const saveCandidateForReview = async () => {
    const candidate = result?.results?.find((item) => item.ok && item.candidate)?.candidate;
    if (!candidate) return;
    setLoading(true);
    setMessage('');
    try {
      const value = await aiFetch('/candidates/draft', { method: 'POST', body: JSON.stringify({ candidate }) });
      setResult((current) => ({ ...current, ...value }));
      setMessage('Candidate saved for human review. It is not published or player-visible.');
    } catch (error) {
      setMessage(error instanceof Error ? error.message : 'Candidate could not be saved.');
    } finally {
      setLoading(false);
    }
  };

  const reviewCandidate = async (id: string, decision: 'approved' | 'rejected' | 'needs_revision') => {
    setLoading(true);
    setMessage('');
    try {
      const value = await aiFetch(`/candidates/${id}/review`, { method: 'POST', body: JSON.stringify({ decision }) });
      setResult((current) => ({
        ...current,
        ...value,
        candidates: current?.candidates?.map((candidate) => candidate.id === id
          ? { ...candidate, status: value.candidate?.status ?? decision, reviewedAt: value.candidate?.reviewedAt ?? candidate.reviewedAt }
          : candidate),
      }));
      setMessage(value.message ?? 'Review recorded. It does not publish a Quest.');
    } catch (error) {
      setMessage(error instanceof Error ? error.message : 'Candidate review could not be saved.');
    } finally {
      setLoading(false);
    }
  };

  const changeVersion = async (action: 'activate' | 'deactivate' | 'restore') => {
    if (!selectedVersion) return;
    setLoading(true);
    setMessage('');
    try {
      const response = await aiFetch(`/prompts/${type}/versions/${selectedVersion}/${action}`, { method: 'POST', body: '{}' });
      setResult(response);
      setMessage(`Prompt version ${selectedVersion} ${action}d.`);
    } catch (error) {
      setMessage(error instanceof Error ? error.message : 'Prompt lifecycle update failed.');
    } finally {
      setLoading(false);
    }
  };

  const savePrompt = async () => {
    setLoading(true);
    setMessage('');
    try {
      const response = await aiFetch(`/prompts/${type}/versions`, {
        method: 'POST',
        body: JSON.stringify({ ...prompt, changeReason: 'Updated from Admin AI Studio' }),
      });
      setResult(response);
      setMessage('New prompt version saved. It remains inactive until explicitly activated.');
    } catch (error) {
      setMessage(error instanceof Error ? error.message : 'Prompt could not be saved.');
    } finally {
      setLoading(false);
    }
  };

  const comparePrompts = async () => {
    if (!selectedVersion || !compareVersion) return;
    setLoading(true);
    setMessage('');
    try {
      const response = await aiFetch(`/prompts/${type}/compare?left=${encodeURIComponent(selectedVersion)}&right=${encodeURIComponent(compareVersion)}`);
      setResult((current) => ({ ...current, ...response }));
    } catch (error) {
      setMessage(error instanceof Error ? error.message : 'Prompt comparison failed.');
    } finally {
      setLoading(false);
    }
  };

  if (!data.session.data?.authorized) {
    return <div className="page-wrap"><PageHeader eyebrow="AI studio" title="AI access unavailable" description="An authorized staff session is required before AI tools can be opened." /><UnavailableState /></div>;
  }
  const requiredAiPermission = location === '/ai/generate'
    ? 'ai.generate'
    : location === '/ai/settings'
      ? 'ai.settings.read'
      : location === '/ai/prompts'
        ? 'ai.prompts.read'
        : 'ai.read';
  if (!data.session.data.permissions.includes(requiredAiPermission)) {
    return <div className="page-wrap"><PageHeader eyebrow="AI studio" title="AI access unavailable" description="Your staff role does not include access to this AI workflow." /><UnavailableState /></div>;
  }
  const canManageQuestCandidates = data.session.data.permissions.includes('admin.quests.manage');
  const title = location === '/ai' ? 'AI Quest Studio' : location === '/ai/prompts' ? 'Prompt templates' : location === '/ai/settings' ? 'AI settings' : 'Generate Quest candidates';
  return (
    <div className="page-wrap">
      <PageHeader eyebrow="AI studio / Quest content" title={title} description="AI creates reviewable Quest candidates only. It never publishes content or writes to the points ledger." />
      {message && <div className="notice" style={{ marginTop: 20 }}><AlertTriangle /><span>{message}</span></div>}
      {location === '/ai/generate' ? (
        <section className="panel" style={{ marginTop: 25 }}>
          <div className="panel-header"><div><div className="panel-title">Generate candidates</div><div className="panel-kicker">TEST GENERATION — NOT SAVED</div></div><span className="tag orange">Draft only</span></div>
          <div className="toolbar">
            <label className="field">Quest type<select value={type} onChange={(event) => setType(event.target.value as typeof type)}><option value="daily">Daily</option><option value="monthly">Monthly</option><option value="geo">Geo</option></select></label>
            <label className="field">Quantity<input type="number" min="1" max="20" value={quantity} onChange={(event) => setQuantity(event.target.value)} /></label>
            {type === 'daily' && <label className="field">Interest Bubble IDs<input value={interestCluster} onChange={(event) => setInterestCluster(event.target.value)} placeholder="Comma-separated Interest Bubble UUIDs" /></label>}
            {type === 'monthly' && <><label className="field">Monthly theme<input value={theme} onChange={(event) => setTheme(event.target.value)} placeholder="Spring reset" /></label><label className="field">Target month<input type="month" value={targetMonth} onChange={(event) => setTargetMonth(event.target.value)} /></label></>}
            {type === 'geo' && <><label className="field">Public location context<input value={locationContext} onChange={(event) => setLocationContext(event.target.value)} placeholder="Public library district" /></label><label className="field">Approximate area<input value={approximateArea} onChange={(event) => setApproximateArea(event.target.value)} placeholder="Downtown" /></label></>}
            <button className="btn btn-primary" onClick={() => void generate()} disabled={loading || !data.session.data.permissions.includes('ai.generate')}>Generate preview</button>
          </div>
          {result?.plan && <div className="notice"><AlertTriangle /><span>{result.plan.diagnostics?.join(' ') || 'Candidate review is required.'} Never publish directly from AI generation.</span></div>}
           {result?.results?.some((item) => item.ok && item.candidate) && <div className="panel-footer"><span className="identity-handle">{result.draft ? `Saved as review draft ${result.draft.id}` : 'Validate the candidate, then send it to the human review queue.'}</span><button className="btn btn-primary" onClick={() => void saveCandidateForReview()} disabled={loading || Boolean(result.draft) || !data.session.data.permissions.includes('admin.quests.manage')}>Save candidate for review</button></div>}
          {result && <pre className="code-panel">{JSON.stringify(result, null, 2)}</pre>}
        </section>
      ) : location === '/ai/prompts' ? (
        <section className="panel" style={{ marginTop: 25 }}>
          <div className="panel-header"><div><div className="panel-title">Independent Quest prompt templates</div><div className="panel-kicker">Every save creates a new version; history is never overwritten</div></div><span className="tag blue">Version {prompt.version ?? 1}</span></div>
           <div className="toolbar"><label className="field">Quest lane<select value={type} onChange={(event) => setType(event.target.value as typeof type)}><option value="daily">Daily</option><option value="monthly">Monthly</option><option value="geo">Geo</option></select></label><label className="field">Version<input value={selectedVersion} onChange={(event) => setSelectedVersion(event.target.value)} inputMode="numeric" /></label><button className="btn btn-quiet" onClick={() => void changeVersion('activate')} disabled={loading || !data.session.data.permissions.includes('ai.prompts.edit')}>Activate</button><button className="btn btn-quiet" onClick={() => void changeVersion('deactivate')} disabled={loading || !data.session.data.permissions.includes('ai.prompts.edit')}>Deactivate</button><button className="btn btn-quiet" onClick={() => void changeVersion('restore')} disabled={loading || !data.session.data.permissions.includes('ai.prompts.edit')}>Restore as new</button></div>
           <div className="toolbar" style={{ marginTop: 10 }}><label className="field">Compare with<input value={compareVersion} onChange={(event) => setCompareVersion(event.target.value)} inputMode="numeric" placeholder="Another version" /></label><button className="btn btn-quiet" onClick={() => void comparePrompts()} disabled={loading || !selectedVersion || !compareVersion}>Compare immutable versions</button></div>
           {result?.comparison && <div className="notice"><Check /><span>{result.comparison.changedFields?.length ? `Changed fields: ${result.comparison.changedFields.join(', ')}` : 'These prompt versions are identical.'}</span></div>}
          <div className="form-grid">
            {([
              ['systemInstructions', 'System prompt'],
              ['contentInstructions', 'Content instructions'],
              ['safetyInstructions', 'Safety rules'],
              ['pointInstructions', 'Point instructions'],
              ['proofInstructions', 'Proof instructions'],
              ['outputFormat', 'Output format'],
            ] as const).map(([key, label]) => <label className="field" key={key}>{label}<textarea value={prompt[key]} onChange={(event) => setPrompt((current) => ({ ...current, [key]: event.target.value }))} rows={3} /></label>)}
          </div>
          <div className="panel-footer"><span className="identity-handle">Supported types: Daily, Monthly, Geo · no secrets or private user data are available to templates.</span><button className="btn btn-primary" onClick={() => void savePrompt()} disabled={loading || !data.session.data.permissions.includes('ai.prompts.edit')}>Save new version</button></div>
        </section>
      ) : (
        <section className="panel" style={{ marginTop: 25 }}>
          <div className="panel-header"><div><div className="panel-title">{location === '/ai/prompts' ? 'Independent Quest prompts' : 'Configuration status'}</div><div className="panel-kicker">Server-controlled and reviewable</div></div><span className={`tag ${result?.provider?.configured ? 'green' : 'orange'}`}>{result?.provider?.configured ? 'Configured' : 'Unavailable'}</span></div>
           {loading ? <TableSkeleton columns={3} /> : result ? <><div className="notice"><LockKeyhole /><span>Approval keeps a candidate in human-controlled content review. It never publishes a Quest or awards points.</span></div><div className="table-wrap" style={{ marginTop: 18 }}><table className="data-table"><thead><tr><th>Candidate</th><th>Lane</th><th>Reward</th><th>Review</th><th>Action</th></tr></thead><tbody>{result.candidates?.length ? result.candidates.map((candidate) => <tr key={candidate.id}><td><strong>{candidate.title}</strong><div className="identity-handle">{new Date(candidate.createdAt).toLocaleString()}</div></td><td>{candidate.type ?? '—'} · {candidate.difficulty ?? '—'}</td><td>{candidate.points ?? '—'} pts</td><td><StatusBadge status={candidate.status} />{candidate.reviewNotes && <div className="identity-handle">{candidate.reviewNotes}</div>}</td><td>{candidate.status === 'pending_review' && <div className="toolbar"><button className="btn btn-quiet" disabled={loading || !canManageQuestCandidates} onClick={() => void reviewCandidate(candidate.id, 'approved')}>Approve</button><button className="btn btn-quiet" disabled={loading || !canManageQuestCandidates} onClick={() => void reviewCandidate(candidate.id, 'needs_revision')}>Request changes</button><button className="btn btn-quiet" disabled={loading || !canManageQuestCandidates} onClick={() => void reviewCandidate(candidate.id, 'rejected')}>Reject</button></div>}</td></tr>) : <tr><td colSpan={5}>No saved AI Quest candidates are awaiting review.</td></tr>}</tbody></table></div></> : <UnavailableState />}
        </section>
      )}
    </div>
  );
}

const operationConfig: Record<string, { eyebrow: string; title: string; description: string; label: string; helper: string }> = {
  '/hunts': { eyebrow: 'Operations / live content', title: 'Hunt moderation', description: 'Monitor player-created Hunts and route cases that need a closer look.', label: 'Hunt review lane', helper: 'Hunt records and moderation cases will appear here when the platform connection is available.' },
  '/quests/daily': { eyebrow: 'Operations / quest drops', title: 'Daily Quest operations', description: 'Keep the daily content cadence clear, reviewed, and ready for players.', label: 'Daily Quest lane', helper: 'Daily Quest inventory will appear here when the platform connection is available.' },
  '/quests/monthly': { eyebrow: 'Operations / quest drops', title: 'Monthly Quest drops', description: 'Coordinate larger Quest drops and their publishing checkpoints.', label: 'Monthly Quest lane', helper: 'Monthly Quest inventory will appear here when the platform connection is available.' },
  '/quests/geo': { eyebrow: 'Operations / quest drops', title: 'Geo-Quest operations', description: 'Review location-aware Quest content and its operational readiness.', label: 'Geo-Quest lane', helper: 'Geo-Quest inventory will appear here when the platform connection is available.' },
  '/quests/submissions': { eyebrow: 'Review / proof', title: 'Proof review queue', description: 'Resolve submitted Quest proof with a consistent, auditable review posture.', label: 'Proof review', helper: 'Proof submissions will appear here when the review queue service is connected.' },
  '/moderation/media': { eyebrow: 'Review / safety', title: 'Media moderation', description: 'Handle media cases with context, consistency, and a clear record of outcomes.', label: 'Media queue', helper: 'Media moderation cases will appear here when the review queue service is connected.' },
  '/moderation/reports': { eyebrow: 'Review / safety', title: 'Reports queue', description: 'Triage reports from the community and keep high-risk cases visible.', label: 'Reports', helper: 'Community reports will appear here when the review queue service is connected.' },
  '/moderation/anti-cheat': { eyebrow: 'Review / safety', title: 'Anti-cheat review', description: 'Inspect integrity signals before they become player-facing incidents.', label: 'Anti-cheat', helper: 'Anti-cheat cases will appear here when the review queue service is connected.' },
  '/interests': { eyebrow: 'Operations / taxonomy', title: 'Interest Bubble administration', description: 'Keep the interest taxonomy legible and useful across the player experience.', label: 'Interest taxonomy', helper: 'Interest Bubble records will appear here when the platform connection is available.' },
  '/achievements': { eyebrow: 'Operations / progression', title: 'Achievement administration', description: 'Review achievement definitions and the progression signals they create.', label: 'Achievement catalog', helper: 'Achievement records will appear here when the platform connection is available.' },
  '/notifications': { eyebrow: 'Platform / communication', title: 'Administrative notifications', description: 'Review operational notices and delivery state across the platform.', label: 'Notification center', helper: 'Administrative notifications will appear here when the platform connection is available.' },
};

export function OperationsPage({ data }: { data: AdminData }) {
  const [location] = useLocation();
  if (location.startsWith('/moderation/')) return <ModerationOperationsPage data={data} location={location} />;
  if (location === '/notifications') return <NotificationOperationsPage data={data} />;
  if (location === '/interests') return <InterestOperationsPage data={data} />;
  const config = operationConfig[location] || operationConfig['/hunts'];
  const isQuestLane = location.startsWith('/quests/');
  const queues = data.reviewQueues.data?.queues;
  const relevantQueues = queues?.filter((item: any) => item.title.toLowerCase().includes(config.label.toLowerCase().split(' ')[0]) || item.category.toLowerCase().includes(config.label.toLowerCase().split(' ')[0]));
  return (
    <div className="page-wrap">
      <PageHeader eyebrow={config.eyebrow} title={config.title} description={config.description} actions={<RefreshButton onClick={() => { void data.reviewQueues.refetch(); if (isQuestLane) void data.quests.refetch(); }} loading={data.reviewQueues.isFetching || (isQuestLane && data.quests.isFetching)} />} />
      <div className="content-grid" style={{ marginTop: 28 }}>
        <section className="panel">
          <div className="panel-header"><div><div className="panel-title">{config.label}</div><div className="panel-kicker">Live operational data from the platform API</div></div><span className="tag orange">Read only</span></div>
          {isQuestLane ? <QuestLanePreview data={data} location={location} helper={config.helper} /> : <div className="empty-state"><CircleIcon /><strong>Awaiting connected records</strong><p>{config.helper} The console will populate this lane without changing its review workflow.</p></div>}
        </section>
        <section className="panel">
          <div className="panel-header"><div><div className="panel-title">Related queue</div><div className="panel-kicker">Prioritized items only</div></div><ChevronRight style={{ width: 16, color: 'hsl(var(--muted-foreground))' }} /></div>
          <QueueList items={relevantQueues} loading={data.reviewQueues.isLoading} onRetry={() => void data.reviewQueues.refetch()} />
        </section>
      </div>
      <div className="notice" style={{ marginTop: 18 }}><AlertTriangle /><span>The console is online, but each operational dataset reports its own live service state. No missing records are treated as zero.</span></div>
    </div>
  );
}

type Interest = { id: string; slug: string; name: string; description?: string | null; icon_key?: string | null; sort_order: number; is_active: boolean };

function InterestOperationsPage({ data }: { data: AdminData }) {
  const [items, setItems] = useState<Interest[]>([]);
  const [loading, setLoading] = useState(true);
  const [message, setMessage] = useState('');
  const [draft, setDraft] = useState({ slug: '', name: '', description: '', sort_order: '0' });
  const canEdit = data.session.data?.permissions.includes('admin.quests.manage') === true;

  const load = async () => {
    setLoading(true);
    try {
      const response = await fetch('/api/admin/interests', { credentials: 'include' });
      if (!response.ok) throw new Error((await response.json() as { error?: string }).error ?? 'Interest Bubble records are unavailable.');
      setItems((await response.json() as { items: Interest[] }).items);
      setMessage('');
    } catch (error) { setMessage(error instanceof Error ? error.message : 'Interest Bubble records are unavailable.'); }
    finally { setLoading(false); }
  };
  useEffect(() => { void load(); }, []);

  const create = async () => {
    try {
      const response = await fetch('/api/admin/interests', {
        method: 'POST', credentials: 'include', headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ ...draft, sort_order: Number(draft.sort_order) }),
      });
      if (!response.ok) throw new Error((await response.json() as { error?: string }).error ?? 'Could not create Interest Bubble.');
      setDraft({ slug: '', name: '', description: '', sort_order: '0' });
      await load();
    } catch (error) { setMessage(error instanceof Error ? error.message : 'Could not create Interest Bubble.'); }
  };

  const toggle = async (item: Interest) => {
    try {
      const response = await fetch(`/api/admin/interests/${encodeURIComponent(item.id)}`, {
        method: 'PATCH', credentials: 'include', headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ is_active: !item.is_active }),
      });
      if (!response.ok) throw new Error('Could not update Interest Bubble.');
      await load();
    } catch (error) { setMessage(error instanceof Error ? error.message : 'Could not update Interest Bubble.'); }
  };

  return <div className="page-wrap">
    <PageHeader eyebrow="Operations / taxonomy" title="Interest Bubble administration" description="Manage the active Interest Bubble taxonomy used by onboarding and Daily Quest targeting." actions={<RefreshButton onClick={() => void load()} loading={loading} />} />
    {message && <div className="notice" style={{ marginTop: 18 }}><AlertTriangle /><span>{message}</span></div>}
    <section className="panel" style={{ marginTop: 25 }}>
      <div className="panel-header"><div><div className="panel-title">Create Interest Bubble</div><div className="panel-kicker">Only active, staff-managed IDs can target Daily Quests</div></div><Plus style={{ width: 16 }} /></div>
      <div className="toolbar">
        <label className="field">Slug<input value={draft.slug} onChange={(event) => setDraft({ ...draft, slug: event.target.value })} placeholder="urban-gardening" /></label>
        <label className="field">Name<input value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })} placeholder="Urban gardening" /></label>
        <label className="field">Description<input value={draft.description} onChange={(event) => setDraft({ ...draft, description: event.target.value })} placeholder="Optional player-facing description" /></label>
        <button className="btn btn-primary" onClick={() => void create()} disabled={!canEdit || loading || !draft.slug || !draft.name}>Create</button>
      </div>
    </section>
    <section className="panel" style={{ marginTop: 22 }}>
      <div className="panel-header"><div><div className="panel-title">Interest Bubble catalog</div><div className="panel-kicker">Inactive records remain valid for historical data but cannot be newly targeted</div></div><span className="tag blue">{items.length} records</span></div>
      {loading ? <TableSkeleton columns={4} /> : !items.length ? <UnavailableState onRetry={() => void load()} /> : <div className="data-table-wrap"><table className="data-table"><thead><tr><th>Name</th><th>Slug</th><th>Status</th><th>Action</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td><div className="identity-name">{item.name}</div><div className="identity-handle">{item.description || 'No description'}</div></td><td className="mono">{item.slug}</td><td><StatusBadge status={item.is_active ? 'live' : 'failed'} /></td><td><button className="btn btn-quiet" onClick={() => void toggle(item)} disabled={!canEdit}>{item.is_active ? 'Deactivate' : 'Activate'}</button></td></tr>)}</tbody></table></div>}
    </section>
  </div>;
}

function NotificationOperationsPage({ data }: { data: AdminData }) {
  const overview = data.notifications.overview.data;
  const metrics = overview?.metrics;
  const delivery = overview?.delivery ?? [];
  const diagnostics = data.notifications.diagnostics.data as { queueHealth?: string; lastSuccessfulSend?: string | null; lastFailedSend?: string | null; invalidTokenCount?: number } | undefined;
  return <div className="page-wrap">
    <PageHeader eyebrow="Platform / communication" title="Administrative notifications" description="Monitor delivery infrastructure without exposing push tokens or provider credentials." actions={<RefreshButton onClick={() => { void data.notifications.overview.refetch(); void data.notifications.diagnostics.refetch(); }} loading={data.notifications.overview.isFetching} />} />
    <div className="metrics-grid" style={{ marginTop: 26 }}>
      {[
        ['Created today', metrics?.notificationsCreatedToday], ['Push attempts', metrics?.pushAttempts], ['Successful pushes', metrics?.successfulPushes],
        ['Failed sends', metrics?.failedSends], ['Invalid tokens', metrics?.invalidTokens], ['Scheduled pending', metrics?.pendingScheduled], ['Queue backlog', metrics?.queueBacklog],
      ].map(([label, value]) => <div className="metric-card" key={String(label)}><div className="metric-label">{label}</div><div className="metric-value">{value ?? '—'}</div><div className="metric-detail">Platform-reported value</div></div>)}
    </div>
    <div className="content-grid" style={{ marginTop: 22 }}>
      <section className="panel"><div className="panel-header"><div><div className="panel-title">Provider and queue</div><div className="panel-kicker">Server-side delivery status</div></div><StatusBadge status={overview?.provider.configured ? 'configured' : 'unavailable'} /></div>{overview ? <div className="empty-state"><strong>{overview.provider.configured ? 'Provider configured' : 'Push provider unavailable'}</strong><p>{overview.provider.reason ?? 'Delivery health is ready for inspection.'}</p><p className="identity-handle">Persistence: {overview.persistence}</p></div> : <UnavailableState onRetry={() => void data.notifications.overview.refetch()} />}</section>
      <section className="panel"><div className="panel-header"><div><div className="panel-title">Self-test</div><div className="panel-kicker">Only sends to your own registered device</div></div></div><button className="btn btn-primary" onClick={() => data.notifications.test.mutate()} disabled={data.notifications.test.isPending || !data.session.data?.authorized}>Send test notification</button>{data.notifications.test.isSuccess && <p className="identity-handle" style={{ marginTop: 12 }}>Test notification queued for your account.</p>}<div className="notice" style={{ marginTop: 18 }}><LockKeyhole /><span>Provider secrets and raw push tokens are never shown in the Admin Panel.</span></div></section>
    </div>
      <section className="panel" style={{ marginTop: 22 }}>
        <div className="panel-header"><div><div className="panel-title">Recent delivery activity</div><div className="panel-kicker">Safe operational state only · never includes recipient tokens or message content</div></div><StatusBadge status={diagnostics?.queueHealth ?? 'unavailable'} /></div>
        {!delivery.length ? <UnavailableState message="No notification deliveries have been recorded yet." /> : <div className="data-table-wrap"><table className="data-table"><thead><tr><th>Channel</th><th>Status</th><th>Attempts</th><th>Failure category</th><th>Last attempt</th></tr></thead><tbody>{delivery.slice(0, 25).map((item) => <tr key={item.id}><td>{item.channel === 'push' ? 'Push' : 'In-app'}</td><td><StatusBadge status={item.status} /></td><td className="mono">{item.attemptCount}</td><td>{item.failureCategory ?? '—'}</td><td>{fmtDateTime(item.lastAttemptAt ?? item.createdAt)}</td></tr>)}</tbody></table></div>}
      </section>
      <section className="panel" style={{ marginTop: 22 }}>
        <div className="panel-header"><div><div className="panel-title">Delivery diagnostics</div><div className="panel-kicker">Provider health and retry visibility</div></div></div>
        <div className="metrics-grid">
          <div className="metric-card"><div className="metric-label">Queue health</div><div className="metric-value">{diagnostics?.queueHealth ?? '—'}</div><div className="metric-detail">Live server state</div></div>
          <div className="metric-card"><div className="metric-label">Invalid tokens</div><div className="metric-value">{diagnostics?.invalidTokenCount ?? '—'}</div><div className="metric-detail">Disabled after permanent provider failure</div></div>
          <div className="metric-card"><div className="metric-label">Last success</div><div className="metric-value" style={{ fontSize: 16 }}>{fmtDateTime(diagnostics?.lastSuccessfulSend)}</div><div className="metric-detail">Provider accepted push</div></div>
          <div className="metric-card"><div className="metric-label">Last failure</div><div className="metric-value" style={{ fontSize: 16 }}>{fmtDateTime(diagnostics?.lastFailedSend)}</div><div className="metric-detail">Retries stay visible here</div></div>
        </div>
      </section>
    <div className="notice" style={{ marginTop: 18 }}><AlertTriangle /><span>Notification records remain independent from push delivery. A failed push never removes in-app history.</span></div>
  </div>;
}

function ModerationOperationsPage({ data, location }: { data: AdminData; location: string }) {
  const moderation = data.moderation;
  const isReports = location === '/moderation/reports';
  const isAntiCheat = location === '/moderation/anti-cheat';
  const title = isReports ? 'Reports queue' : isAntiCheat ? 'Anti-cheat review' : 'Media moderation';
  const eyebrow = isReports ? 'Review / safety' : isAntiCheat ? 'Review / integrity' : 'Review / safety';
  const cases = moderation.cases.data?.items ?? [];
  const filteredCases = isAntiCheat ? [] : cases.filter((item) => !isReports || item.sourceReportIds.length > 0);
  const snapshots = moderation.snapshots.data?.items ?? [];
  return (
    <div className="page-wrap">
      <PageHeader eyebrow={eyebrow} title={title} description={isReports ? 'Triage normalized community reports, merge duplicates, and route urgent public-safety cases.' : isAntiCheat ? 'Review privacy-safe integrity snapshots without turning contextual signals into automatic guilt.' : 'Review media safety outcomes with a human decision required for enforcement.'} actions={<RefreshButton onClick={() => { void moderation.cases.refetch(); void moderation.reports.refetch(); void moderation.snapshots.refetch(); void moderation.diagnostics.refetch(); }} loading={moderation.cases.isFetching} />} />
      {moderation.diagnostics.data?.state && <div className="metrics-grid" style={{ marginTop: 26 }}>
        {Object.entries(moderation.diagnostics.data.state.counts).map(([label, value]) => <div className="metric-card" key={label}><div className="metric-label">{label.replace(/[A-Z]/g, (letter) => ` ${letter}`).replace(/^./, (letter) => letter.toUpperCase())}</div><div className="metric-value">{value}</div><div className="metric-detail">Policy {moderation.diagnostics.data?.state?.policyVersion}</div></div>)}
      </div>}
      {isAntiCheat ? <section className="panel" style={{ marginTop: 22 }}>
        <div className="panel-header"><div><div className="panel-title">Integrity snapshots</div><div className="panel-kicker">Scores are contextual signals · no raw location shown</div></div><StatusBadge status={moderation.diagnostics.data?.state?.persistence ?? 'unavailable'} /></div>
        {moderation.snapshots.isLoading ? <TableSkeleton columns={4} /> : !snapshots.length ? <UnavailableState message="No integrity snapshots have been recorded yet." /> : <div className="data-table-wrap"><table className="data-table"><thead><tr><th>Risk band</th><th>Score</th><th>Entity</th><th>Captured</th></tr></thead><tbody>{snapshots.slice(0, 25).map((item) => <tr key={item.id}><td><StatusBadge status={item.riskBand} /></td><td className="mono">{item.score}</td><td>{item.entityType} · <span className="mono">{item.entityId}</span></td><td>{fmtDateTime(item.createdAt)}</td></tr>)}</tbody></table></div>}
      </section> : <div className="content-grid" style={{ marginTop: 22 }}>
        <section className="panel">
          <div className="panel-header"><div><div className="panel-title">{isReports ? 'Report intake' : 'Moderation cases'}</div><div className="panel-kicker">Human review lane · {moderation.cases.data?.persistence ?? 'connected state'}</div></div><StatusBadge status={moderation.cases.isError ? 'failed' : 'live'} /></div>
          {moderation.cases.isLoading ? <TableSkeleton columns={4} /> : moderation.cases.isError ? <ErrorState onRetry={() => void moderation.cases.refetch()} /> : !filteredCases.length ? <UnavailableState message={isReports ? 'No report-linked cases have been recorded.' : 'No media cases are waiting for review.'} onRetry={() => void moderation.cases.refetch()} /> : <div>{filteredCases.map((item) => <CaseRow item={item} key={item.id} onClaim={() => moderation.claim.mutate(item.id)} onResolve={(decision) => { if (!window.confirm(`Confirm ${decision.replace(/_/g, ' ')} for this case? This action is recorded and cannot be silently undone.`)) return; const reason = window.prompt('Decision reason (required)'); if (reason?.trim()) moderation.resolve.mutate({ id: item.id, decision, reason: reason.trim(), expectedUpdatedAt: item.updatedAt }); }} />)}</div>}
        </section>
        <section className="panel">
          <div className="panel-header"><div><div className="panel-title">{isReports ? 'Normalized reports' : 'Review guidance'}</div><div className="panel-kicker">{isReports ? 'Duplicate-aware intake' : 'Conservative by design'}</div></div></div>
          {isReports ? <div>{(moderation.reports.data?.items ?? []).slice(0, 12).map((report) => <div className="queue-row" key={report.id}><div className={`queue-mark ${report.priority}`}><Flag style={{ width: 15 }} /></div><div className="queue-copy"><div className="queue-title">{report.reason.replace(/_/g, ' ')}</div><div className="queue-meta">{report.entityType} · {report.relatedReportIds.length} related · {fmtDateTime(report.createdAt)}</div></div><StatusBadge status={report.status} /></div>)}</div> : <div className="empty-state"><ShieldCheck /><strong>Safety and validity stay separate</strong><p>Automated signals can prioritize and quarantine. Only a trusted moderator can remove content, restrict an account, or reverse a reward.</p></div>}
        </section>
      </div>}
      <div className="notice" style={{ marginTop: 18 }}><AlertTriangle /><span>Internal scores, provider responses, reporter identity, exact locations, and private proof media are never shown in this console view.</span></div>
    </div>
  );
}

function CaseRow({ item, onClaim, onResolve }: { item: import('@/hooks/use-admin-data').ModerationCase; onClaim: () => void; onResolve: (decision: 'no_action' | 'warning' | 'content_removed' | 'account_restricted' | 'account_suspended' | 'quarantine' | 'release' | 'reverse') => void }) {
  return <div className="queue-row" style={{ alignItems: 'flex-start' }} data-testid={`moderation-case-${item.id}`}><div className={`queue-mark ${item.priority}`}><ShieldCheck style={{ width: 15 }} /></div><div className="queue-copy"><div className="queue-title">{item.entityType} · {item.entityId}</div><div className="queue-meta">{item.context} · opened {fmtDateTime(item.createdAt)}{item.assignedModeratorId ? ` · claimed` : ''}</div><div style={{ display: 'flex', gap: 7, marginTop: 9, flexWrap: 'wrap' }}><StatusBadge status={item.priority} /><StatusBadge status={item.status} />{item.outcome?.action && <StatusBadge status={item.outcome.action} />}</div></div><div style={{ display: 'flex', gap: 6, flexWrap: 'wrap', justifyContent: 'flex-end' }}>{!item.assignedModeratorId && item.status !== 'resolved' && <button className="btn btn-quiet" onClick={onClaim}>Claim</button>}{item.status !== 'resolved' && <button className="btn btn-primary" onClick={() => onResolve('no_action')}>Resolve</button>}</div></div>;
}

function QuestLanePreview({ data, location, helper }: { data: AdminData; location: string; helper: string }) {
  const type = location.split('/').pop();
  const items = data.quests.data?.items.filter((quest: any) => quest.type === type);
  if (data.quests.isLoading) return <TableSkeleton columns={4} />;
  if (data.quests.isError) return <ErrorState onRetry={() => void data.quests.refetch()} />;
  if (!items) return <UnavailableState message={helper} onRetry={() => void data.quests.refetch()} />;
  if (!items.length) return <div className="empty-state"><CircleIcon /><strong>No {type} Quest records returned</strong><p>{helper}</p></div>;
  return <div>{items.slice(0, 8).map((quest: any) => <div className="queue-row" key={quest.id}><div className="queue-mark"><TargetIcon /></div><div className="queue-copy"><div className="queue-title">{quest.title}</div><div className="queue-meta">{quest.source} · updated {fmtDate(quest.updatedAt)}</div></div><StatusBadge status={quest.status} /></div>)}</div>;
}

function CircleIcon() {
  return <div style={{ width: 28, height: 28, border: '1px dashed hsl(var(--accent))', borderRadius: '50%', margin: '0 auto 11px' }} />;
}

export function SettingsPage({ data }: { data: AdminData }) {
  const [saved, setSaved] = useState(false);
  const [strictReview, setStrictReview] = useState(true);
  const [auditRetention, setAuditRetention] = useState('365');
  const moderationSettings = data.moderation.settings.data?.settings;
  const [automationEnabled, setAutomationEnabled] = useState(false);
  const [approvalMode, setApprovalMode] = useState<'manual_only' | 'low_risk' | 'mixed'>('manual_only');
  useEffect(() => {
    if (moderationSettings) {
      setAutomationEnabled(moderationSettings.automationEnabled);
      setApprovalMode(moderationSettings.autoApprovalMode);
    }
  }, [moderationSettings]);
  const saveModerationSettings = () => {
    data.moderation.updateSettings.mutate({ automationEnabled, autoApprovalMode: approvalMode });
    setSaved(true);
  };
  return (
    <div className="page-wrap">
      <PageHeader eyebrow="Platform / controls" title="Typed platform settings" description="Configuration surfaces for staff operations. Changes are explicit and never hidden behind defaults." />
      <div className="notice" style={{ marginTop: 26 }}><LockKeyhole /><span>Changes are server-controlled. Until Supabase is connected, the API reports local-development-only persistence and never presents it as production data.</span></div>
      <section className="panel" style={{ marginTop: 18, maxWidth: 900 }}>
        <div className="panel-header"><div><div className="panel-title">Review posture</div><div className="panel-kicker">Controls that affect staff-facing review behavior</div></div><span className="tag blue">Session preview</span></div>
        <div className="form-grid">
          <div className="field"><label htmlFor="retention">Audit retention window</label><select id="retention" value={auditRetention} onChange={(event) => { setAuditRetention(event.target.value); setSaved(false); }} data-testid="select-audit-retention"><option value="90">90 days</option><option value="365">365 days</option><option value="730">730 days</option></select></div>
          <div className="field"><label htmlFor="strict-review">Strict proof review</label><select id="strict-review" value={strictReview ? 'on' : 'off'} onChange={(event) => { setStrictReview(event.target.value === 'on'); setSaved(false); }} data-testid="select-strict-review"><option value="on">Enabled</option><option value="off">Disabled</option></select></div>
        </div>
        <div className="form-footer"><button className="btn btn-primary" onClick={() => setSaved(true)} data-testid="button-save-settings">{saved ? <><Check /> Saved for session</> : 'Save settings'}</button></div>
      </section>
      <section className="panel" style={{ marginTop: 18, maxWidth: 900 }}>
        <div className="panel-header"><div><div className="panel-title">Moderation automation</div><div className="panel-kicker">Provider output never replaces trusted human review</div></div><StatusBadge status={moderationSettings?.persistence ?? (data.moderation.settings.isLoading ? 'checking' : 'unavailable')} /></div>
        {data.moderation.settings.isError ? <UnavailableState message="Moderation settings are unavailable until an approved staff session and server persistence are available." /> : <div className="form-grid">
          <div className="field"><label htmlFor="moderation-automation">Automation</label><select id="moderation-automation" value={automationEnabled ? 'on' : 'off'} onChange={(event) => { setAutomationEnabled(event.target.value === 'on'); setSaved(false); }}><option value="off">Disabled — manual review</option><option value="on">Enabled — configured provider only</option></select></div>
          <div className="field"><label htmlFor="moderation-approval-mode">Approval posture</label><select id="moderation-approval-mode" value={approvalMode} onChange={(event) => { setApprovalMode(event.target.value as typeof approvalMode); setSaved(false); }}><option value="manual_only">Manual only</option><option value="low_risk">Low-risk public content</option><option value="mixed">Mixed policy</option></select></div>
        </div>}
        <div className="form-footer"><button className="btn btn-primary" onClick={saveModerationSettings} disabled={data.moderation.updateSettings.isPending || !moderationSettings} data-testid="button-save-moderation-settings">{data.moderation.updateSettings.isPending ? 'Saving…' : 'Save moderation settings'}</button></div>
      </section>
    </div>
  );
}
