import { useMemo, useState } from 'react';
import { Link, useLocation } from 'wouter';
import { AlertTriangle, ArrowUpRight, Check, ChevronRight, Database, FileText, LockKeyhole, Search, SlidersHorizontal, UsersRound } from 'lucide-react';
import { useAdminData } from '@/hooks/use-admin-data';
import { DiagnosticsList, ErrorState, MetricGrid, PageHeader, QueueList, RefreshButton, StatusBadge, UnavailableState } from '@/components/admin-ui';

type AdminData = ReturnType<typeof useAdminData>;

const fmtDate = (value?: string | null) => value ? new Date(value).toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' }) : '—';
const fmtDateTime = (value?: string | null) => value ? new Date(value).toLocaleString(undefined, { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' }) : '—';
const initials = (name: string) => name.split(/\s+/).slice(0, 2).map((part) => part[0]).join('').toUpperCase();

export function DashboardPage({ data }: { data: AdminData }) {
  const dashboard = data.dashboard.data;
  const queues = data.reviewQueues.data?.queues;
  return (
    <div className="page-wrap">
      <PageHeader eyebrow="Workspace / today" title="Good morning, operator." description="A concise view of what needs attention across the Worlds platform." actions={<RefreshButton onClick={() => { void data.dashboard.refetch(); void data.reviewQueues.refetch(); }} loading={data.dashboard.isFetching} />} />
      <div style={{ display: 'flex', alignItems: 'center', gap: 7, color: 'hsl(var(--muted-foreground))', fontSize: 11, margin: '24px 0 12px' }}>
        <span className="status-dot" style={{ width: 6, height: 6 }} /> Last generated {dashboard?.generatedAt ? fmtDateTime(dashboard.generatedAt) : '—'}
      </div>
      <MetricGrid metrics={dashboard?.metrics} loading={data.dashboard.isLoading} />
      <div className="content-grid">
        <section className="panel">
          <div className="panel-header"><div><div className="panel-title">Priority queue</div><div className="panel-kicker">Items ordered by operational urgency</div></div><Link href="/quests/submissions" className="btn btn-quiet" style={{ minHeight: 32, padding: '0 9px' }} data-testid="link-view-all-queue">View queue <ArrowUpRight /></Link></div>
          {data.dashboard.isError ? <ErrorState onRetry={() => void data.dashboard.refetch()} /> : <QueueList items={dashboard?.actionQueue} loading={data.dashboard.isLoading} onRetry={() => void data.dashboard.refetch()} />}
        </section>
        <section className="panel">
          <div className="panel-header"><div><div className="panel-title">Review queues</div><div className="panel-kicker">Current moderation lanes</div></div><SlidersHorizontal style={{ width: 15, color: 'hsl(var(--muted-foreground))' }} /></div>
          <QueueList items={queues} loading={data.reviewQueues.isLoading} onRetry={() => void data.reviewQueues.refetch()} />
        </section>
      </div>
      <div className="notice" style={{ marginTop: 18 }}><Database /><span><strong>Operational note:</strong> dashboard figures are read-only snapshots generated by the platform. A missing value means the underlying service is unavailable, not zero.</span></div>
    </div>
  );
}

export function UsersPage({ data }: { data: AdminData }) {
  const [search, setSearch] = useState('');
  const [status, setStatus] = useState('all');
  const users = data.users.data?.items;
  const filtered = useMemo(() => users?.filter((user) => `${user.displayName} ${user.username} ${user.role}`.toLowerCase().includes(search.toLowerCase()) && (status === 'all' || user.accountStatus === status)), [users, search, status]);
  const statuses = Array.from(new Set(users?.map((user) => user.accountStatus) || []));
  return (
    <div className="page-wrap">
      <PageHeader eyebrow="Operations / people" title="User directory" description="Search staff-facing identity and activity signals without leaving the operations console." actions={<RefreshButton onClick={() => void data.users.refetch()} loading={data.users.isFetching} />} />
      <div className="toolbar">
        <div className="search-box"><Search /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search by name or username" aria-label="Search users" data-testid="input-search-users" /></div>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}><label className="eyebrow" htmlFor="user-status-filter">Status</label><select id="user-status-filter" value={status} onChange={(event) => setStatus(event.target.value)} style={{ border: '1px solid hsl(var(--input))', background: 'hsl(var(--card))', borderRadius: 6, padding: '9px 10px', color: 'hsl(var(--foreground))', fontSize: 12 }} data-testid="select-user-status"><option value="all">All accounts</option>{statuses.map((item) => <option value={item} key={item}>{item.replace(/_/g, ' ')}</option>)}</select></div>
      </div>
      <section className="panel">
        <div className="panel-header"><div><div className="panel-title">All users</div><div className="panel-kicker">{data.users.data?.total ?? '—'} records returned · page 1</div></div><UsersRound style={{ width: 17, color: 'hsl(var(--muted-foreground))' }} /></div>
        {data.users.isError ? <ErrorState onRetry={() => void data.users.refetch()} /> : data.users.isLoading ? <TableSkeleton columns={5} /> : !users ? <UnavailableState onRetry={() => void data.users.refetch()} /> : !filtered?.length ? <div className="empty-state"><Search /><strong>No matching users</strong><p>Try a different name, username, or account status.</p></div> : <div className="data-table-wrap"><table className="data-table"><thead><tr><th>Identity</th><th>Role</th><th>Account</th><th>Activity</th><th>Points</th><th>Open cases</th></tr></thead><tbody>{filtered.map((user) => <tr key={user.id} data-testid={`row-user-${user.id}`}><td><div className="identity"><div className="avatar">{initials(user.displayName)}</div><div><div className="identity-name" data-testid={`text-user-name-${user.id}`}>{user.displayName}</div><div className="identity-handle">@{user.username}</div></div></div></td><td><StatusBadge status={user.role} /></td><td><StatusBadge status={user.accountStatus} /></td><td><div style={{ fontWeight: 600 }}>{fmtDate(user.lastActiveAt)}</div><div className="identity-handle">Joined {fmtDate(user.createdAt)}</div></td><td className="mono">{user.totalPoints ?? '—'}</td><td><span className={user.openCases ? 'tag red' : 'tag'}>{user.openCases ?? '—'}</span></td></tr>)}</tbody></table></div>}
      </section>
    </div>
  );
}

export function QuestsPage({ data }: { data: AdminData }) {
  const [search, setSearch] = useState('');
  const [type, setType] = useState('all');
  const quests = data.quests.data?.items;
  const filtered = useMemo(() => quests?.filter((quest) => `${quest.title} ${quest.source}`.toLowerCase().includes(search.toLowerCase()) && (type === 'all' || quest.type === type)), [quests, search, type]);
  return (
    <div className="page-wrap">
      <PageHeader eyebrow="Operations / content" title="Quest administration" description="Review the content pipeline, publishing state, and proof load across every Quest format." actions={<RefreshButton onClick={() => void data.quests.refetch()} loading={data.quests.isFetching} />} />
      <div className="tab-row" data-testid="quest-section-tabs"><Link className={`tab ${type === 'all' ? 'active' : ''}`} href="/quests" data-testid="link-quest-tab-all">All quests</Link><Link className="tab" href="/quests/daily" data-testid="link-quest-tab-daily">Daily</Link><Link className="tab" href="/quests/monthly" data-testid="link-quest-tab-monthly">Monthly</Link><Link className="tab" href="/quests/geo" data-testid="link-quest-tab-geo">Geo</Link><Link className="tab" href="/quests/submissions" data-testid="link-quest-tab-submissions">Proof review</Link></div>
      <div className="toolbar"><div className="search-box"><Search /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search Quest title or source" aria-label="Search quests" data-testid="input-search-quests" /></div><select value={type} onChange={(event) => setType(event.target.value)} style={{ border: '1px solid hsl(var(--input))', background: 'hsl(var(--card))', borderRadius: 6, padding: '9px 10px', color: 'hsl(var(--foreground))', fontSize: 12 }} data-testid="select-quest-type"><option value="all">Every type</option><option value="daily">Daily</option><option value="monthly">Monthly</option><option value="geo">Geo</option></select></div>
      <section className="panel">
        <div className="panel-header"><div><div className="panel-title">Quest catalog</div><div className="panel-kicker">{data.quests.data?.total ?? '—'} records returned · sorted by latest update</div></div><TargetIcon /></div>
        {data.quests.isError ? <ErrorState onRetry={() => void data.quests.refetch()} /> : data.quests.isLoading ? <TableSkeleton columns={6} /> : !quests ? <UnavailableState onRetry={() => void data.quests.refetch()} /> : !filtered?.length ? <div className="empty-state"><Search /><strong>No matching Quests</strong><p>There are no records matching this search and type filter.</p></div> : <div className="data-table-wrap"><table className="data-table"><thead><tr><th>Quest</th><th>Type</th><th>Status</th><th>Difficulty</th><th>Completions</th><th>Reviews</th><th>Updated</th></tr></thead><tbody>{filtered.map((quest) => <tr key={quest.id} data-testid={`row-quest-${quest.id}`}><td><div className="identity-name">{quest.title}</div><div className="identity-handle">{quest.source} · {quest.points ?? '—'} pts</div></td><td><span className="tag blue">{quest.type}</span></td><td><StatusBadge status={quest.status} /></td><td>{quest.difficulty || '—'}</td><td className="mono">{quest.completionCount ?? '—'}</td><td className="mono">{quest.reviewCount ?? '—'}</td><td>{fmtDate(quest.updatedAt)}</td></tr>)}</tbody></table></div>}
      </section>
    </div>
  );
}

function TargetIcon() {
  return <div style={{ width: 29, height: 29, borderRadius: 7, background: 'hsl(var(--accent) / .16)', display: 'grid', placeItems: 'center', color: 'hsl(24 71% 41%)' }}><ArrowUpRight style={{ width: 15 }} /></div>;
}

function TableSkeleton({ columns }: { columns: number }) {
  return <div className="data-table-wrap"><table className="data-table"><tbody>{[1, 2, 3, 4, 5].map((row) => <tr key={row}>{Array.from({ length: columns }).map((_, col) => <td key={col}><div className="skeleton" style={{ height: 13, width: col === 0 ? '80%' : '52%' }} /></td>)}</tr>)}</tbody></table></div>;
}

export function AuditPage({ data }: { data: AdminData }) {
  const [search, setSearch] = useState('');
  const events = data.audit.data?.items;
  const filtered = events?.filter((event) => `${event.actor} ${event.action} ${event.entityType} ${event.entity}`.toLowerCase().includes(search.toLowerCase()));
  return (
    <div className="page-wrap">
      <PageHeader eyebrow="Platform / accountability" title="Audit log" description="An append-only view of staff actions and their recorded outcomes." actions={<RefreshButton onClick={() => void data.audit.refetch()} loading={data.audit.isFetching} />} />
      <div className="notice" style={{ marginTop: 25 }}><LockKeyhole /><span>Audit events are immutable. This view is for investigation and traceability; it does not expose controls to alter history.</span></div>
      <div className="toolbar"><div className="search-box"><Search /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search actor, action, or entity" aria-label="Search audit log" data-testid="input-search-audit" /></div><span className="mono" style={{ color: 'hsl(var(--muted-foreground))', fontSize: 10 }}>{data.audit.data?.total ?? '—'} EVENTS</span></div>
      <section className="panel">{data.audit.isError ? <ErrorState onRetry={() => void data.audit.refetch()} /> : data.audit.isLoading ? <TableSkeleton columns={5} /> : !events ? <UnavailableState onRetry={() => void data.audit.refetch()} /> : !filtered?.length ? <div className="empty-state"><FileLogIcon /><strong>No audit events found</strong><p>Nothing matches this search in the returned event page.</p></div> : <div className="data-table-wrap"><table className="data-table"><thead><tr><th>Timestamp</th><th>Actor</th><th>Action</th><th>Entity</th><th>Result</th><th>Reason</th></tr></thead><tbody>{filtered.map((event) => <tr key={event.id} data-testid={`row-audit-${event.id}`}><td className="mono" style={{ whiteSpace: 'nowrap', fontSize: 10 }}>{fmtDateTime(event.timestamp)}</td><td><div style={{ fontWeight: 600 }}>{event.actor || 'System'}</div><div className="identity-handle">{event.actorRole || '—'}</div></td><td>{event.action}</td><td>{event.entityType}{event.entity ? <div className="identity-handle">{event.entity}</div> : null}</td><td><StatusBadge status={event.result} /></td><td style={{ maxWidth: 240, color: 'hsl(var(--muted-foreground))' }}>{event.reason || '—'}</td></tr>)}</tbody></table></div>}</section>
    </div>
  );
}

function FileLogIcon() {
  return <FileText style={{ color: 'hsl(var(--accent))' }} />;
}

export function DiagnosticsPage({ data }: { data: AdminData }) {
  const diagnostics = data.diagnostics.data;
  const unavailableCount = diagnostics?.checks.filter((check) => ['missing', 'degraded', 'failed', 'unavailable'].includes(check.status)).length || 0;
  return (
    <div className="page-wrap">
      <PageHeader eyebrow="Platform / health" title="Diagnostics" description="Safe, read-only checks for the services that power staff operations." actions={<RefreshButton onClick={() => void data.diagnostics.refetch()} loading={data.diagnostics.isFetching} />} />
      <div style={{ display: 'flex', gap: 10, margin: '26px 0 17px', flexWrap: 'wrap' }}><span className="tag green" data-testid="status-diagnostics-summary">{diagnostics ? `${diagnostics.checks.length - unavailableCount} healthy` : 'Status unavailable'}</span>{diagnostics && unavailableCount > 0 && <span className="tag orange">{unavailableCount} need attention</span>}<span className="mono" style={{ alignSelf: 'center', fontSize: 10, color: 'hsl(var(--muted-foreground))' }}>{diagnostics?.generatedAt ? `Generated ${fmtDateTime(diagnostics.generatedAt)}` : 'Awaiting platform response'}</span></div>
      {data.diagnostics.isError ? <div className="panel"><ErrorState onRetry={() => void data.diagnostics.refetch()} /></div> : <DiagnosticsList checks={diagnostics?.checks} loading={data.diagnostics.isLoading} onRetry={() => void data.diagnostics.refetch()} />}
    </div>
  );
}

const operationConfig: Record<string, { eyebrow: string; title: string; description: string; label: string; helper: string }> = {
  '/hunts': { eyebrow: 'Operations / live content', title: 'Hunt moderation', description: 'Monitor player-created Hunts and route cases that need a closer look.', label: 'Hunt review lane', helper: 'Hunt records and moderation cases will appear here when the platform connection is available.' },
  '/quests/daily': { eyebrow: 'Operations / quest drops', title: 'Daily Quest operations', description: 'Keep the daily content cadence clear, reviewed, and ready for players.', label: 'Daily Quest lane', helper: 'Daily Quest inventory will appear here when the platform connection is available.' },
  '/quests/monthly': { eyebrow: 'Operations / quest drops', title: 'Monthly Quest drops', description: 'Coordinate larger Quest drops and their publishing checkpoints.', label: 'Monthly Quest lane', helper: 'Monthly Quest inventory will appear here when the platform connection is available.' },
  '/quests/geo': { eyebrow: 'Operations / quest drops', title: 'Geo-Quest operations', description: 'Review location-aware Quest content and its operational readiness.', label: 'Geo-Quest lane', helper: 'Geo-Quest inventory will appear here when the platform connection is available.' },
  '/quests/submissions': { eyebrow: 'Review / proof', title: 'Proof review queue', description: 'Resolve submitted Quest proof with a consistent, auditable review posture.', label: 'Proof review', helper: 'Proof submissions will appear here when the review queue service is connected.' },
  '/moderation/media': { eyebrow: 'Review / safety', title: 'Media moderation', description: 'Handle media cases with context, consistency, and a clear record of outcomes.', label: 'Media queue', helper: 'Media moderation cases will appear here when the review queue service is connected.' },
  '/moderation/reports': { eyebrow: 'Review / safety', title: 'Reports queue', description: 'Triage reports from the community and keep high-risk cases visible.', label: 'Reports', helper: 'Community reports will appear here when the review queue service is connected.' },
  '/moderation/anti-cheat': { eyebrow: 'Review / safety', title: 'Anti-cheat review', description: 'Inspect integrity signals before they become player-facing incidents.', label: 'Anti-cheat', helper: 'Anti-cheat cases will appear here when the review queue service is connected.' },
  '/interests': { eyebrow: 'Operations / taxonomy', title: 'Interest Bubble administration', description: 'Keep the interest taxonomy legible and useful across the player experience.', label: 'Interest taxonomy', helper: 'Interest Bubble records will appear here when the platform connection is available.' },
  '/achievements': { eyebrow: 'Operations / progression', title: 'Achievement administration', description: 'Review achievement definitions and the progression signals they create.', label: 'Achievement catalog', helper: 'Achievement records will appear here when the platform connection is available.' },
  '/notifications': { eyebrow: 'Platform / communication', title: 'Administrative notifications', description: 'Review operational notices and delivery state across the platform.', label: 'Notification center', helper: 'Administrative notifications will appear here when the platform connection is available.' },
};

export function OperationsPage({ data }: { data: AdminData }) {
  const [location] = useLocation();
  const config = operationConfig[location] || operationConfig['/hunts'];
  const isQuestLane = location.startsWith('/quests/');
  const queues = data.reviewQueues.data?.queues;
  const relevantQueues = queues?.filter((item) => item.title.toLowerCase().includes(config.label.toLowerCase().split(' ')[0]) || item.category.toLowerCase().includes(config.label.toLowerCase().split(' ')[0]));
  return (
    <div className="page-wrap">
      <PageHeader eyebrow={config.eyebrow} title={config.title} description={config.description} actions={<RefreshButton onClick={() => { void data.reviewQueues.refetch(); if (isQuestLane) void data.quests.refetch(); }} loading={data.reviewQueues.isFetching || (isQuestLane && data.quests.isFetching)} />} />
      <div className="content-grid" style={{ marginTop: 28 }}>
        <section className="panel">
          <div className="panel-header"><div><div className="panel-title">{config.label}</div><div className="panel-kicker">Live operational data from the platform API</div></div><span className="tag orange">Read only</span></div>
          {isQuestLane ? <QuestLanePreview data={data} location={location} helper={config.helper} /> : <div className="empty-state"><CircleIcon /><strong>Awaiting connected records</strong><p>{config.helper} The console will populate this lane without changing its review workflow.</p></div>}
        </section>
        <section className="panel">
          <div className="panel-header"><div><div className="panel-title">Related queue</div><div className="panel-kicker">Prioritized items only</div></div><ChevronRight style={{ width: 16, color: 'hsl(var(--muted-foreground))' }} /></div>
          <QueueList items={relevantQueues} loading={data.reviewQueues.isLoading} onRetry={() => void data.reviewQueues.refetch()} />
        </section>
      </div>
      <div className="notice" style={{ marginTop: 18 }}><AlertTriangle /><span>This lane is intentionally truthful about its connection state. No local placeholder records are presented as real platform data.</span></div>
    </div>
  );
}

function QuestLanePreview({ data, location, helper }: { data: AdminData; location: string; helper: string }) {
  const type = location.split('/').pop();
  const items = data.quests.data?.items.filter((quest) => quest.type === type);
  if (data.quests.isLoading) return <TableSkeleton columns={4} />;
  if (data.quests.isError) return <ErrorState onRetry={() => void data.quests.refetch()} />;
  if (!items) return <UnavailableState message={helper} onRetry={() => void data.quests.refetch()} />;
  if (!items.length) return <div className="empty-state"><CircleIcon /><strong>No {type} Quest records returned</strong><p>{helper}</p></div>;
  return <div>{items.slice(0, 8).map((quest) => <div className="queue-row" key={quest.id}><div className="queue-mark"><TargetIcon /></div><div className="queue-copy"><div className="queue-title">{quest.title}</div><div className="queue-meta">{quest.source} · updated {fmtDate(quest.updatedAt)}</div></div><StatusBadge status={quest.status} /></div>)}</div>;
}

function CircleIcon() {
  return <div style={{ width: 28, height: 28, border: '1px dashed hsl(var(--accent))', borderRadius: '50%', margin: '0 auto 11px' }} />;
}

export function SettingsPage() {
  const [saved, setSaved] = useState(false);
  const [strictReview, setStrictReview] = useState(true);
  const [auditRetention, setAuditRetention] = useState('365');
  return (
    <div className="page-wrap">
      <PageHeader eyebrow="Platform / controls" title="Typed platform settings" description="Configuration surfaces for staff operations. Changes are explicit and never hidden behind defaults." />
      <div className="notice" style={{ marginTop: 26 }}><LockKeyhole /><span>These controls are presented as typed platform settings. Supabase-backed persistence is not available in this artifact yet, so changes are held in this session only.</span></div>
      <section className="panel" style={{ marginTop: 18, maxWidth: 900 }}>
        <div className="panel-header"><div><div className="panel-title">Review posture</div><div className="panel-kicker">Controls that affect staff-facing review behavior</div></div><span className="tag blue">Session preview</span></div>
        <div className="form-grid">
          <div className="field"><label htmlFor="retention">Audit retention window</label><select id="retention" value={auditRetention} onChange={(event) => { setAuditRetention(event.target.value); setSaved(false); }} data-testid="select-audit-retention"><option value="90">90 days</option><option value="365">365 days</option><option value="730">730 days</option></select></div>
          <div className="field"><label htmlFor="strict-review">Strict proof review</label><select id="strict-review" value={strictReview ? 'on' : 'off'} onChange={(event) => { setStrictReview(event.target.value === 'on'); setSaved(false); }} data-testid="select-strict-review"><option value="on">Enabled</option><option value="off">Disabled</option></select></div>
        </div>
        <div className="form-footer"><button className="btn btn-primary" onClick={() => setSaved(true)} data-testid="button-save-settings">{saved ? <><Check /> Saved for session</> : 'Save settings'}</button></div>
      </section>
    </div>
  );
}